import Foundation
import Observation

enum RealStrategyExplanationState: Sendable { case idle, loading, loaded, refreshing, offlineCached, empty, error(String) }

@MainActor @Observable final class RealStrategyExplanationStore {
    var state: RealStrategyExplanationState = .idle; var sessionID: String?; var explanation: StrategyExplanation?; var isLoading = false; var isRefreshing = false; var error: String?; var lastUpdatedAt: Date?; var isOffline = false
    private let repository: RealStrategyExplanationRepository; private let authSession: AuthenticationSession; private let appState: AppState; private let ttl: TimeInterval; private var cache: [String: (StrategyExplanation, Date)] = [:]; private var tasks: [String: Task<Void, Never>] = [:]; private var generations: [String: Int] = [:]
    init(repository: RealStrategyExplanationRepository, authSession: AuthenticationSession, appState: AppState, ttl: TimeInterval = 30) { self.repository = repository; self.authSession = authSession; self.appState = appState; self.ttl = ttl }
    func load(sessionID id: String, reason: String = "sectionOpened", force: Bool = false) async { self.sessionID = id; BotaplataLog.strategyExplanation.info("StrategyExplanationStore.load session=\(id, privacy: .public) reason=\(reason, privacy: .public)"); if let task = tasks[id] { BotaplataLog.strategyExplanation.info("StrategyExplanationStore.load skipped reason=singleFlight session=\(id, privacy: .public)"); await task.value; return }; if !force, let c = cache[id], Date().timeIntervalSince(c.1) < ttl { BotaplataLog.strategyExplanation.info("StrategyExplanationStore.cache status=hit"); apply(c.0, state: .loaded, stale: c.0.analysis.freshness.isStale); return }; BotaplataLog.strategyExplanation.info("StrategyExplanationStore.cache status=miss"); let existing = cache[id]?.0; state = existing == nil ? .loading : .refreshing; isLoading = existing == nil; isRefreshing = existing != nil; error = nil; generations[id, default: 0] += 1; let g = generations[id]!
        let task = Task { [repository, authSession] in do { let value = try await authSession.withAccessTokenReplay { token in try await repository.fetchStrategyExplanation(sessionID: id, accessToken: token) }; try Task.checkCancellation(); await MainActor.run { guard self.generations[id] == g else { return }; self.cache[id] = (value, Date()); self.apply(value, state: .loaded, stale: value.analysis.freshness.isStale) } } catch is CancellationError { } catch AuthenticationError.accessTokenExpired { await MainActor.run { self.appState.transition(to: .expired) } } catch AuthenticationError.deviceRevoked { await MainActor.run { self.appState.transition(to: .revoked) } } catch { await MainActor.run { self.applyError(error, cached: existing) } } }
        tasks[id] = task; await task.value; tasks[id] = nil }
    func refresh(sessionID id: String) async { await load(sessionID: id, reason: "manualRefresh", force: true) }
    func cancel(sessionID id: String) { tasks[id]?.cancel(); tasks[id] = nil; generations[id, default: 0] += 1; isLoading = false; isRefreshing = false }
    private func apply(_ value: StrategyExplanation, state: RealStrategyExplanationState, stale: Bool) { explanation = value; self.state = value.conditions.isEmpty && value.indicators.indicators.isEmpty ? .empty : state; isOffline = false; isLoading = false; isRefreshing = false; lastUpdatedAt = Date(); BotaplataLog.strategyExplanation.info("StrategyExplanationStore.loaded session=\(value.sessionID, privacy: .public) stale=\(stale, privacy: .public)") }
    private func applyError(_ error: Error, cached: StrategyExplanation?) { let text: String; if (error as? AuthenticationError) == .offline { text = "Erreur réseau" } else if (error as? AuthenticationError) == .contractIncompatible { text = "Contrat incompatible" } else if (error as? AuthenticationError) == .validationError { text = "Session inexistante" } else { text = "Erreur serveur" }; self.error = text; isLoading = false; isRefreshing = false; if let cached { explanation = cached; isOffline = true; state = .offlineCached } else { explanation = nil; isOffline = false; state = .error(text) } }
}
