import Foundation
import Observation

@MainActor @Observable final class RealSessionHistoryStore {
    var timelines: [String: LoadedContent<[TimelineEvent]>] = [:]; var timelinePagination: [String: RealSessionsPagination] = [:]
    var orders: [String: LoadedContent<[SessionOrder]>] = [:]; var ordersPagination: [String: RealSessionsPagination] = [:]
    var decisions: [String: LoadedContent<[SessionDecision]>] = [:]; var decisionsPagination: [String: RealSessionsPagination] = [:]
    var charts: [String: LoadedContent<SessionChart>] = [:]; var warnings: [String: [Warning]] = [:]
    private let repository: RealSessionHistoryRepository; private let cache: RealSessionHistoryCache; private let authSession: AuthenticationSession; private let appState: AppState; private let pageSize: Int
    private var tasks: [String: Task<Void, Never>] = [:]; private var generations: [String: Int] = [:]
    init(repository: RealSessionHistoryRepository, cache: RealSessionHistoryCache, authSession: AuthenticationSession, appState: AppState, pageSize: Int = 50) { self.repository = repository; self.cache = cache; self.authSession = authSession; self.appState = appState; self.pageSize = pageSize }
    func loadCache() async { if let c = await cache.load() { for (id, p) in c.timelines { timelines[id] = .loadedFromCache(p.items); timelinePagination[id] = p.pagination }; for (id, chart) in c.charts { charts[id] = .loadedFromCache(chart) } } }
    func purge() async { tasks.values.forEach { $0.cancel() }; tasks = [:]; timelines = [:]; timelinePagination = [:]; orders = [:]; ordersPagination = [:]; decisions = [:]; decisionsPagination = [:]; charts = [:]; warnings = [:]; await cache.purge() }
    func refreshTimeline(sessionID: String) async { await loadTimeline(sessionID: sessionID, page: 1, append: false) }
    func loadNextTimeline(sessionID: String) async { guard timelinePagination[sessionID]?.hasMore == true else { return }; await loadTimeline(sessionID: sessionID, page: (timelinePagination[sessionID]?.page ?? 1) + 1, append: true) }
    func refreshOrders(sessionID: String) async { await loadOrders(sessionID: sessionID, page: 1, append: false) }
    func loadNextOrders(sessionID: String) async { guard ordersPagination[sessionID]?.hasMore == true else { return }; await loadOrders(sessionID: sessionID, page: (ordersPagination[sessionID]?.page ?? 1) + 1, append: true) }
    func refreshDecisions(sessionID: String) async { await loadDecisions(sessionID: sessionID, page: 1, append: false) }
    func loadNextDecisions(sessionID: String) async { guard decisionsPagination[sessionID]?.hasMore == true else { return }; await loadDecisions(sessionID: sessionID, page: (decisionsPagination[sessionID]?.page ?? 1) + 1, append: true) }
    func refreshChart(sessionID: String) async { let key = "chart:\(sessionID)"; if let t = tasks[key] { await t.value; return }; charts[sessionID] = chartValue(sessionID).map { .refreshing($0) } ?? .loading; bump(key); let g = generations[key]!
        let task = Task { [repository, authSession, cache] in do { let chart = try await Self.authorized(authSession: authSession) { try await repository.fetchChart(sessionID: sessionID, accessToken: $0) }; try Task.checkCancellation(); await MainActor.run { if self.generations[key] == g { self.charts[sessionID] = .loaded(chart); self.warnings[sessionID] = chart.warnings } }; await cache.saveChart(sessionID: sessionID, chart: chart) } catch { await MainActor.run { self.handle(error, key: key) { self.charts[sessionID] = self.chartValue(sessionID).map { .offline($0) } ?? .error("Impossible de charger le graphique") } } } }; tasks[key] = task; await task.value; tasks[key] = nil }
    private func loadTimeline(sessionID: String, page: Int, append: Bool) async { await loadPage(key: "timeline:\(sessionID)", current: timelineItems(sessionID), setLoading: { timelines[sessionID] = append ? .partial(timelineItems(sessionID)) : (timelineItems(sessionID).isEmpty ? .loading : .refreshing(timelineItems(sessionID))) }, fetch: { try await repository.fetchTimeline(sessionID: sessionID, page: page, pageSize: pageSize, accessToken: $0) }, apply: { p in timelinePagination[sessionID] = p.pagination; timelines[sessionID] = .loaded(merge(timelineItems(sessionID), p.items, append)); warnings[sessionID] = p.warnings; if page == 1 { await cache.saveTimeline(sessionID: sessionID, page: p) } }) }
    private func loadOrders(sessionID: String, page: Int, append: Bool) async { await loadPage(key: "orders:\(sessionID)", current: orderItems(sessionID), setLoading: { orders[sessionID] = append ? .partial(orderItems(sessionID)) : (orderItems(sessionID).isEmpty ? .loading : .refreshing(orderItems(sessionID))) }, fetch: { try await repository.fetchOrders(sessionID: sessionID, page: page, pageSize: pageSize, accessToken: $0) }, apply: { p in ordersPagination[sessionID] = p.pagination; orders[sessionID] = .loaded(merge(orderItems(sessionID), p.items, append)); warnings[sessionID] = p.warnings }) }
    private func loadDecisions(sessionID: String, page: Int, append: Bool) async { await loadPage(key: "decisions:\(sessionID)", current: decisionItems(sessionID), setLoading: { decisions[sessionID] = append ? .partial(decisionItems(sessionID)) : (decisionItems(sessionID).isEmpty ? .loading : .refreshing(decisionItems(sessionID))) }, fetch: { try await repository.fetchDecisions(sessionID: sessionID, page: page, pageSize: pageSize, accessToken: $0) }, apply: { p in decisionsPagination[sessionID] = p.pagination; decisions[sessionID] = .loaded(merge(decisionItems(sessionID), p.items, append)); warnings[sessionID] = p.warnings }) }
    private func loadPage<Page, Item>(key: String, current: [Item], setLoading: @escaping () -> Void, fetch: @escaping @Sendable (String) async throws -> Page, apply: @escaping (Page) async -> Void) async { if let t = tasks[key] { await t.value; return }; setLoading(); bump(key); let g = generations[key]!; let task = Task { [authSession] in do { let page = try await Self.authorized(authSession: authSession, operation: fetch); try Task.checkCancellation(); await MainActor.run { if self.generations[key] == g { Task { await apply(page) } } } } catch { await MainActor.run { self.handle(error, key: key) { if key.hasPrefix("timeline:") { let id = String(key.dropFirst("timeline:".count)); self.timelines[id] = self.timelineItems(id).isEmpty ? .error("Impossible de charger le Journal") : .offline(self.timelineItems(id)) } else if key.hasPrefix("orders:") { let id = String(key.dropFirst("orders:".count)); self.orders[id] = self.orderItems(id).isEmpty ? .error("Impossible de charger les ordres") : .offline(self.orderItems(id)) } else if key.hasPrefix("decisions:") { let id = String(key.dropFirst("decisions:".count)); self.decisions[id] = self.decisionItems(id).isEmpty ? .error("Impossible de charger les décisions") : .offline(self.decisionItems(id)) } } } } }; tasks[key] = task; await task.value; tasks[key] = nil }
    private func handle(_ error: Error, key: String, fallback: () -> Void) { if let e = error as? AuthenticationError, e == .accessTokenExpired { appState.transition(to: .expired) } else if let e = error as? AuthenticationError, e == .deviceRevoked { appState.transition(to: .revoked) } else { fallback() } }
    private func bump(_ key: String) { generations[key, default: 0] += 1 }
    private static func authorized<T>(authSession: AuthenticationSession, operation: @escaping @Sendable (String) async throws -> T) async throws -> T { try await authSession.withAccessTokenReplay(operation) }
    func timelineItems(_ id: String) -> [TimelineEvent] { items(timelines[id]) }; func orderItems(_ id: String) -> [SessionOrder] { items(orders[id]) }; func decisionItems(_ id: String) -> [SessionDecision] { items(decisions[id]) }; func chartValue(_ id: String) -> SessionChart? { value(charts[id]) }
}
private func items<T>(_ c: LoadedContent<[T]>?) -> [T] { switch c { case .loaded(let v), .loadedFromCache(let v), .refreshing(let v?), .partial(let v), .stale(let v), .offline(let v?): v; default: [] } }
private func value<T>(_ c: LoadedContent<T>?) -> T? { switch c { case .loaded(let v), .loadedFromCache(let v), .refreshing(let v?), .stale(let v), .offline(let v?): v; default: nil } }
private func merge<T: Identifiable>(_ old: [T], _ new: [T], _ append: Bool) -> [T] where T.ID: Hashable { var base = append ? old : []; var ids = Set(base.map(\.id)); for i in new where !ids.contains(i.id) { base.append(i); ids.insert(i.id) }; return base }
