import SwiftUI
import Charts

struct ChartRenderableCandle: Identifiable, Equatable { let id: String; let openTime: Date; let closeTime: Date; let isClosed: Bool; let open: Double; let high: Double; let low: Double; let close: Double; let volume: Double?; let vwap: Double?; let ema200: Double?; let bollingerUpper: Double?; let bollingerMiddle: Double?; let bollingerLower: Double?; var positive: Bool { close >= open } }
struct RealTradingChartRenderModel: Equatable { let chart: TradingChart; let candles: [ChartRenderableCandle]; let hasVWAP: Bool; let hasEMA200: Bool; let hasBollinger: Bool; let hasVolume: Bool; static func make(chart: TradingChart) -> Self { let cs = chart.candles.map { ChartRenderableCandle(id: $0.id, openTime: $0.openTime, closeTime: $0.closeTime, isClosed: $0.isClosed, open: dbl($0.open), high: dbl($0.high), low: dbl($0.low), close: dbl($0.close), volume: $0.volume.map(dbl), vwap: $0.vwap.map(dbl), ema200: $0.ema200.map(dbl), bollingerUpper: $0.bollingerUpper.map(dbl), bollingerMiddle: $0.bollingerMiddle.map(dbl), bollingerLower: $0.bollingerLower.map(dbl)) }; return .init(chart: chart, candles: cs, hasVWAP: cs.contains { $0.vwap != nil }, hasEMA200: cs.contains { $0.ema200 != nil }, hasBollinger: cs.contains { $0.bollingerUpper != nil || $0.bollingerMiddle != nil || $0.bollingerLower != nil }, hasVolume: cs.contains { $0.volume != nil }) } }
private func dbl(_ d: Decimal) -> Double { NSDecimalNumber(decimal: d).doubleValue }

struct RealTradingChartSection: View { let session: SessionDetail; @Environment(RealSessionChartStore.self) private var store; var body: some View { RealTradingChartView(state: store.state, selectedRange: store.selectedRange, select: { store.selectRange($0, sessionID: session.id) }, refresh: { store.refresh(sessionID: session.id) }).task(id: session.id) { store.load(sessionID: session.id) }.onDisappear { store.stop() }.refreshable { store.refresh(sessionID: session.id) } } }

struct RealTradingChartView: View { let state: RealSessionChartState; let selectedRange: TradingChartRange; let select: (TradingChartRange) -> Void; let refresh: () -> Void; @State private var showVWAP = true; @State private var showEMA200 = true; @State private var showBollinger = false; @State private var selected: ChartRenderableCandle?
    var body: some View { ScrollView { LazyVStack(alignment: .leading, spacing: BotaplataSpacing.md) { ChartRangeSelector(selected: selectedRange, select: select); content }.padding() } }
    @ViewBuilder private var content: some View { switch state { case .idle, .loading: PremiumSkeletonCard(); PremiumSkeletonCard(); case .failed(let e): PremiumErrorState(title: e.title, message: e.message); case .loaded(let c), .refreshing(let c), .offline(let c): let m = RealTradingChartRenderModel.make(chart: c); if case .offline = state { PremiumOfflineBanner() }; if c.candles.isEmpty { PremiumEmptyState(title: "Graphique en préparation", message: c.warnings.first?.message ?? "Le serveur ne dispose pas encore d’un historique de prix suffisant pour afficher le graphique.") } else { MarketSummary(chart: c); IndicatorControls(model: m, showVWAP: $showVWAP, showEMA200: $showEMA200, showBollinger: $showBollinger); CandlestickChart(model: m, showVWAP: showVWAP, showEMA200: showEMA200, showBollinger: showBollinger, selected: $selected); if m.hasVolume { VolumeChart(candles: m.candles) }; if let selected { ChartTooltip(candle: selected, quote: c.quoteAsset) }; ChartLevelsSummary(levels: c.levels, quote: c.quoteAsset); ChartLegend(model: m); ForEach(c.warnings) { WarningBanner(warning: $0) }; Text("Dernière actualisation : \(HistoryPresentation.fullDate(c.generatedAt))").font(.caption).foregroundStyle(BotaplataColors.textSecondary) } } }
}
struct ChartRangeSelector: View { let selected: TradingChartRange; let select: (TradingChartRange) -> Void; var body: some View { HStack { ForEach(TradingChartRange.allCases, id: \.self) { r in Button(r.displayTitle) { select(r) }.buttonStyle(.borderedProminent).tint(r == selected ? BotaplataColors.primaryTeal : BotaplataColors.elevated).accessibilityLabel("Période \(r.displayTitle), \(r == selected ? "sélectionnée" : "non sélectionnée")") } } } }
struct CandlestickChart: View { let model: RealTradingChartRenderModel; let showVWAP: Bool; let showEMA200: Bool; let showBollinger: Bool; @Binding var selected: ChartRenderableCandle?; var body: some View { PremiumCard { Chart { ForEach(model.candles) { c in RuleMark(x: .value("Date", c.openTime), yStart: .value("Bas", c.low), yEnd: .value("Haut", c.high)).foregroundStyle(c.positive ? BotaplataColors.success : BotaplataColors.danger); RectangleMark(x: .value("Date", c.openTime), yStart: .value("Ouverture", c.open), yEnd: .value("Clôture", c.close), width: .fixed(5)).foregroundStyle(c.positive ? BotaplataColors.success : BotaplataColors.danger).opacity(c.isClosed ? 1 : 0.55).accessibilityLabel("Bougie ouverture \(c.open) haut \(c.high) bas \(c.low) clôture \(c.close)") ; if showVWAP, let v = c.vwap { LineMark(x: .value("Date", c.openTime), y: .value("VWAP", v)).foregroundStyle(BotaplataColors.accentCyan) }; if showEMA200, let e = c.ema200 { LineMark(x: .value("Date", c.openTime), y: .value("EMA200", e)).foregroundStyle(BotaplataColors.warning) }; if showBollinger, let b = c.bollingerUpper { LineMark(x: .value("Date", c.openTime), y: .value("Bollinger haute", b)).foregroundStyle(BotaplataColors.textMuted) }; if showBollinger, let b = c.bollingerMiddle { LineMark(x: .value("Date", c.openTime), y: .value("Bollinger centrale", b)).foregroundStyle(BotaplataColors.textSecondary) }; if showBollinger, let b = c.bollingerLower { LineMark(x: .value("Date", c.openTime), y: .value("Bollinger basse", b)).foregroundStyle(BotaplataColors.textMuted) } } }.frame(height: 300) } } }
struct VolumeChart: View { let candles: [ChartRenderableCandle]; var body: some View { PremiumCard { Chart(candles.compactMap { $0.volume == nil ? nil : $0 }) { BarMark(x: .value("Date", $0.openTime), y: .value("Volume", $0.volume ?? 0)).foregroundStyle(BotaplataColors.accentCyan.opacity(0.55)) }.frame(height: 80) } } }
struct IndicatorControls: View { let model: RealTradingChartRenderModel; @Binding var showVWAP: Bool; @Binding var showEMA200: Bool; @Binding var showBollinger: Bool; var body: some View { HStack { if model.hasVWAP { Toggle("VWAP", isOn: $showVWAP) }; if model.hasEMA200 { Toggle("EMA200", isOn: $showEMA200) }; if model.hasBollinger { Toggle("Bollinger", isOn: $showBollinger) } }.font(.caption) } }
struct MarketSummary: View { let chart: TradingChart; var body: some View { PremiumCard { VStack(alignment: .leading) { Text("Résumé du marché").font(BotaplataTypography.cardTitle); PremiumKeyValueRow(label: "Dernier prix", value: FinancialFormatters.decimal(chart.candles.last?.close, suffix: chart.quoteAsset)); PremiumKeyValueRow(label: "Plus haut", value: FinancialFormatters.decimal(chart.candles.map(\.high).max(), suffix: chart.quoteAsset)); PremiumKeyValueRow(label: "Plus bas", value: FinancialFormatters.decimal(chart.candles.map(\.low).min(), suffix: chart.quoteAsset)); PremiumKeyValueRow(label: "Timeframe", value: chart.timeframe); PremiumKeyValueRow(label: "Bougies", value: String(chart.candles.count)) } } } }
struct ChartTooltip: View { let candle: ChartRenderableCandle; let quote: String; var body: some View { PremiumCard { Text("OHLC \(candle.open) / \(candle.high) / \(candle.low) / \(candle.close) \(quote)").font(.caption).monospacedDigit() } } }
struct ChartLevelsSummary: View { let levels: TradingLevels; let quote: String; var body: some View { PremiumCard { VStack(alignment: .leading) { Text("Niveaux financiers").font(BotaplataTypography.cardTitle); row("Prix d’entrée", levels.entryPrice); row("Seuil de rentabilité", levels.breakEvenPrice); row("Prix minimum rentable", levels.minimumProfitableExitPrice); row("Trailing stop", levels.trailingStopPrice) } } }
    private func row(_ t: String, _ v: Decimal?) -> some View { PremiumKeyValueRow(label: t, value: FinancialFormatters.decimal(v, suffix: quote)) } }
struct ChartLegend: View { let model: RealTradingChartRenderModel; var body: some View { Text("Légende : hausse, baisse, bougie ouverte, VWAP, EMA200, Bollinger, marqueurs backend et niveaux persistés.").font(.caption).foregroundStyle(BotaplataColors.textSecondary) } }
extension FinancialFormatters { static func decimal(_ value: Decimal?, suffix: String) -> String { guard let value else { return "—" }; return "\(NSDecimalNumber(decimal: value).stringValue) \(suffix)" } }
