import SwiftUI

struct SessionsView: View { let sessions: [SessionSummary]
    var body: some View { List { Text("Données temporaires — onglets Sessions/Journal non connectés dans cette PR.").font(.caption).foregroundStyle(BotaplataColors.warning); ForEach(sessions) { session in NavigationLink { SessionDetailView(session: PreviewFixtures.detail(for: session.id)) } label: { VStack(alignment: .leading, spacing: 8) { HStack { Text(session.pair).font(.headline); ProviderBadge(provider: session.provider) }; Text(session.lifecycle.label); FreshnessBadge(freshness: session.freshness); if session.provider == .binanceLegacy { Text("Historique Binance — lecture seule, non recommandé").font(.caption).foregroundStyle(BotaplataColors.warning) } } } } }.navigationTitle("Sessions").scrollContentBackground(.hidden).background(BotaplataColors.background) }
}
struct SessionDetailView: View { let session: SessionDetail; var body: some View { ScrollView { SessionDetailContent(session: session, compact: false).padding() }.background(BotaplataColors.background.ignoresSafeArea()).navigationTitle(session.pair) } }
struct SessionDetailContent: View { let session: SessionDetail; let compact: Bool
    var body: some View { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { SectionHeader(title: session.pair, subtitle: DashboardPresentation.wording(for: session.lifecycle).text); HStack { ProviderBadge(provider: session.provider); FreshnessBadge(freshness: session.freshness) }; BotaplataCard { VStack(alignment:.leading, spacing: 10) { Text("État prioritaire").font(.headline); StatusBadge(status: session.lifecycle == .stopped ? .neutral : .active, text: session.lifecycle.label); StatusBadge(status: session.runtimeHealth == .healthy ? .success : .warning, text: session.runtimeHealth.label); if session.runtimeHealth == .degraded { Text("La surveillance rencontre actuellement un problème.") } } }; metrics; decision; if let order = session.activeOrder { orderView(order) }; feeAware } }
    var metrics: some View { LazyVGrid(columns: [GridItem(.adaptive(minimum: 150))], spacing: 12) { MetricTile(title: "Prix actuel", value: session.currentPrice?.value == nil ? "Prix indisponible" : FinancialFormatters.money(session.currentPrice), footnote: nil); MetricTile(title: "Quantité", value: session.position?.quantity.map { FinancialFormatters.decimal($0, min: 2, max: 6) } ?? "—", footnote: "Absence non convertie"); MetricTile(title: "Prix moyen exécuté", value: FinancialFormatters.money(session.position?.averageExecutionPrice), footnote: nil); MetricTile(title: "Prix de revient frais inclus", value: FinancialFormatters.money(session.position?.costBasisPrice), footnote: "Frais inclus si fourni") } }
    var decision: some View { BotaplataCard { Text(session.decision.title).font(.headline); Text(session.decision.detail).foregroundStyle(.secondary) } }
    func orderView(_ order: TradingOrderSummary) -> some View { BotaplataCard { Text("Ordre actif").font(.headline); StatusBadge(status: order.status == .filled ? .success : order.status == .rejected ? .danger : .waiting, text: order.status.label); Text(order.message) } }
    var feeAware: some View { BotaplataCard { VStack(alignment:.leading, spacing: 8) { Text("Données financières fee-aware").font(.headline); row("Frais achat", FinancialFormatters.money(session.feeAware.buyFeeQuote)); row("Seuil de rentabilité", FinancialFormatters.money(session.feeAware.breakEvenPrice)); row("PnL brut", FinancialFormatters.money(session.feeAware.unrealizedPnLGrossQuote)); row("PnL net estimé", FinancialFormatters.money(session.feeAware.unrealizedPnLNetEstimatedQuote)); Text("Le résultat net estimé tient compte des frais d'achat réels, des frais de vente estimés et du slippage estimé.").font(.caption).foregroundStyle(.secondary) } } }
    func row(_ k: String, _ v: String) -> some View { HStack { Text(k); Spacer(); Text(v).monospacedDigit() } }
}
#Preview { NavigationStack { SessionsView(sessions: PreviewFixtures.sessionSummaries) } }
