import SwiftUI

struct SessionsContainerView: View { @State var store: RealSessionsStore
    var body: some View { SessionsView(content: store.content, warnings: store.warnings, loadNext: { id in await store.loadNextPageIfNeeded(currentItemID: id) }, refresh: { await store.refresh() }, detailContent: { id in store.details[id] ?? .idle }, loadDetail: { id in await store.loadDetail(id: id) }).task { store.start() } }
}

struct SessionsView: View {
    let content: LoadedContent<[SessionSummary]>; var warnings: [Warning] = []; var loadNext: (String?) async -> Void = { _ in }; var refresh: () async -> Void = {}; var detailContent: (String) -> LoadedContent<SessionDetail> = { _ in .idle }; var loadDetail: (String) async -> Void = { _ in }
    var body: some View { List { if isOffline { Text("Connexion momentanément indisponible. Dernier état connu affiché.").font(.caption).foregroundStyle(BotaplataColors.warning) }; ForEach(warnings) { warning in Text(warning.message).font(.caption).foregroundStyle(BotaplataColors.warning) }; contentView }.navigationTitle("Sessions").scrollContentBackground(.hidden).background(BotaplataColors.background).refreshable { await refresh() } }
    @ViewBuilder var contentView: some View { switch content { case .idle, .loading: sessionsSkeleton; case .error: EmptyStateView(title: "Impossible de charger les sessions", message: "Vérifiez votre connexion puis réessayez."); case .loaded(let items), .loadedFromCache(let items), .refreshing(let items?), .offline(let items?), .partial(let items), .stale(let items): if items.isEmpty { EmptyStateView(title: "Aucune session réelle", message: "Aucune session Kraken réelle n'est disponible pour le moment.") } else { sections(items) }; case .refreshing(nil), .offline(nil): EmptyStateView(title: "Impossible de charger les sessions", message: "Vérifiez votre connexion puis réessayez.") } }
    var isOffline: Bool { if case .offline = content { true } else { false } }
    var sessionsSkeleton: some View { ForEach(0..<3, id: \.self) { _ in BotaplataCard { VStack(alignment: .leading) { Text("Chargement des sessions…").font(.headline); Text("Dernier état connu recherché").foregroundStyle(.secondary) } } } }
    func sections(_ items: [SessionSummary]) -> some View { Group { let active = items.filter { !$0.isHistorical }; let history = items.filter(\.isHistorical); if !active.isEmpty { Section("En cours") { rows(active) } }; if !history.isEmpty { Section("Historique") { rows(history) } } } }
    func rows(_ items: [SessionSummary]) -> some View { ForEach(items) { session in NavigationLink(value: session.id) { SessionRow(session: session).task { await loadNext(session.id) } }.accessibilityLabel(accessibility(for: session)) }.navigationDestination(for: String.self) { id in SessionDetailContainerView(sessionID: id, content: detailContent(id), load: { await loadDetail(id) }) } }
    func accessibility(for s: SessionSummary) -> String { "\(s.pair.replacingOccurrences(of: "/", with: " ")), \(s.providerLabel ?? s.provider.displayName), \(DashboardPresentation.wording(for: s.lifecycle).title), \(s.runtimeHealth.label), \(freshnessText(s.freshness))." }
}

struct SessionRow: View { let session: SessionSummary
    var body: some View { VStack(alignment: .leading, spacing: 8) { HStack { Text(session.pair).font(.headline); Spacer(); ProviderBadge(provider: session.provider) }; Text(DashboardPresentation.wording(for: session.lifecycle).title).font(.subheadline.weight(.semibold)); Text(session.runtimeHealth.label).font(.caption).foregroundStyle(session.runtimeHealth == .degraded ? BotaplataColors.warning : .secondary); Text(freshnessText(session.freshness)).font(.caption).foregroundStyle(.secondary); if let pnl = session.unrealizedPnLQuote, pnl.value != nil { Text("Résultat latent : \(FinancialFormatters.money(pnl))").font(.caption).monospacedDigit() } }.padding(.vertical, 6) }
}

struct SessionDetailContainerView: View { let sessionID: String; let content: LoadedContent<SessionDetail>; let load: () async -> Void
    var body: some View { ScrollView { Group { switch content { case .loaded(let s), .refreshing(let s?), .offline(let s?), .stale(let s), .loadedFromCache(let s): SessionDetailContent(session: s, compact: false); case .error: EmptyStateView(title: "Session indisponible", message: "Vérifiez votre connexion puis réessayez."); default: BotaplataCard { Text("Chargement du détail…").font(.headline); Text("Botaplata récupère le détail consolidé.").foregroundStyle(.secondary) } } }.padding() }.background(BotaplataColors.background.ignoresSafeArea()).task { await load() } }
}
struct SessionDetailView: View { let session: SessionDetail; var body: some View { ScrollView { SessionDetailContent(session: session, compact: false).padding() }.background(BotaplataColors.background.ignoresSafeArea()).navigationTitle(session.pair) } }
struct SessionDetailContent: View { let session: SessionDetail; let compact: Bool
    var body: some View { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { let wording = DashboardPresentation.wording(for: session.lifecycle); SectionHeader(title: session.pair, subtitle: wording.text); HStack { ProviderBadge(provider: session.provider); FreshnessBadge(freshness: session.freshness) }; ForEach(session.warnings) { Text($0.message).font(.caption).foregroundStyle(BotaplataColors.warning) }; stateCard; marketPosition; decision; if let order = session.activeOrder { orderView(order) }; if let reconciliation = session.reconciliation { BotaplataCard { Text(reconciliation.title).font(.headline); Text(reconciliation.message).foregroundStyle(.secondary) } }; feeAware; pnlCard } }
    var stateCard: some View { BotaplataCard { VStack(alignment:.leading, spacing: 10) { Text("État de la session").font(.headline); StatusBadge(status: session.lifecycle == .stopped ? .neutral : .active, text: DashboardPresentation.wording(for: session.lifecycle).title); StatusBadge(status: session.runtimeHealth == .healthy ? .success : .warning, text: session.runtimeHealth.label); Text(freshnessText(session.freshness)).foregroundStyle(.secondary); if let errors = session.monitoringConsecutiveErrors, errors > 0 { Text("\(errors) erreurs consécutives").foregroundStyle(BotaplataColors.warning) } } } }
    var marketPosition: some View { LazyVGrid(columns: [GridItem(.adaptive(minimum: 150))], spacing: 12) { MetricTile(title: "Prix actuel", value: session.currentPrice?.value == nil ? "Prix indisponible" : FinancialFormatters.money(session.currentPrice), footnote: nil); if let position = session.position { MetricTile(title: "Quantité", value: position.quantity.map { FinancialFormatters.decimal($0, min: 2, max: 6) } ?? "Indisponible", footnote: nil); MetricTile(title: "Prix moyen exécuté", value: FinancialFormatters.money(position.averageExecutionPrice), footnote: nil); MetricTile(title: "Prix de revient frais inclus", value: FinancialFormatters.money(position.costBasisPrice), footnote: "Frais inclus si fourni") } } }
    var decision: some View { BotaplataCard { Text("Dernière décision").font(.headline); Text(session.decision.title).font(.subheadline.weight(.semibold)); Text(session.decision.detail).foregroundStyle(.secondary) } }
    func orderView(_ order: TradingOrderSummary) -> some View { BotaplataCard { Text("Ordre actif").font(.headline); Text(order.side); StatusBadge(status: order.status == .filled ? .success : order.status == .rejected ? .danger : .waiting, text: order.status.label); Text(order.message).foregroundStyle(.secondary) } }
    var feeAware: some View { BotaplataCard { VStack(alignment:.leading, spacing: 8) { Text("Données financières fee-aware").font(.headline); row("Prix de revient frais inclus", FinancialFormatters.money(session.feeAware.costBasisPrice)); row("Seuil de rentabilité", FinancialFormatters.money(session.feeAware.breakEvenPrice)); row("Prix minimum rentable", FinancialFormatters.money(session.feeAware.minimumProfitableExitPrice)); row("Résultat brut", FinancialFormatters.money(session.feeAware.unrealizedPnLGrossQuote)); row("Résultat net estimé", FinancialFormatters.money(session.feeAware.unrealizedPnLNetEstimatedQuote)); Text("Le résultat net estimé tient compte des frais d'achat réels, des frais de vente estimés et du slippage estimé.").font(.caption).foregroundStyle(.secondary) } } }
    var pnlCard: some View { BotaplataCard { VStack(alignment:.leading, spacing: 8) { Text("Résultat").font(.headline); row("Résultat latent", FinancialFormatters.money(session.pnl?.gross)); row("Résultat net réalisé", FinancialFormatters.money(session.pnl?.realizedNet)) } } }
    func row(_ k: String, _ v: String) -> some View { HStack { Text(k); Spacer(); Text(v == "—" ? "Indisponible" : v).monospacedDigit() } }
}

func freshnessText(_ freshness: DataFreshness) -> String { guard let date = freshness.updatedAt else { return "Fraîcheur inconnue" }; let seconds = max(0, Int(Date().timeIntervalSince(date))); if freshness.status == .stale { return "Dernière donnée connue il y a \(relative(seconds))" }; return "Mis à jour il y a \(relative(seconds))" }
private func relative(_ seconds: Int) -> String { seconds < 60 ? "\(seconds) s" : seconds < 3600 ? "\(seconds / 60) min" : "\(seconds / 3600) h" }

#Preview("Sessions réelles") { NavigationStack { SessionsView(content: .loaded(PreviewFixtures.sessionSummaries)) } }
#Preview("Sessions vides") { NavigationStack { SessionsView(content: .loaded([])) } }
#Preview("Offline cache") { NavigationStack { SessionsView(content: .offline(PreviewFixtures.sessionSummaries)) } }
#Preview("Détail waiting buy") { NavigationStack { SessionDetailView(session: PreviewFixtures.waitingBuy) } }
#Preview("Détail waiting sell") { NavigationStack { SessionDetailView(session: PreviewFixtures.krakenDetail) } }
#Preview("Reconciliation") { NavigationStack { SessionDetailView(session: PreviewFixtures.waitingBuyFill) } }
