import SwiftUI

struct DashboardView: View {
    let content: LoadedContent<RealActiveSnapshot>
    var refresh: (() async -> Void)? = nil
    init(content: LoadedContent<RealActiveSnapshot>, refresh: (() async -> Void)? = nil) { self.content = content; self.refresh = refresh }
    init(summary: DashboardSummary) { self.content = .loaded(RealActiveSnapshot(generatedAt: nil, activeSessionCount: summary.activeSession == nil ? 0 : 1, activeSession: summary.activeSession, warnings: summary.warnings, requestID: nil, serverTime: nil)); self.refresh = nil }
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { header; bodyContent }.padding() }.refreshable { await refresh?() }.background(BotaplataColors.background.ignoresSafeArea()).navigationTitle("Dashboard") }
    @ViewBuilder var bodyContent: some View { switch content { case .idle, .loading: ProgressView("Chargement du dernier état…"); case .error(let message): EmptyStateView(title: "Snapshot indisponible", message: message); case .loaded(let s): snapshot(s, cached: false, offline: false); case .loadedFromCache(let s): snapshot(s, cached: true, offline: false); case .refreshing(let s?): snapshot(s, cached: false, offline: false); case .stale(let s), .offline(let s?): snapshot(s, cached: true, offline: true); case .partial(let s): snapshot(s, cached: false, offline: false); case .refreshing(nil), .offline(nil): EmptyStateView(title: "Snapshot indisponible", message: "Réessayez lorsque la connexion est disponible.") } }
    func snapshot(_ snapshot: RealActiveSnapshot, cached: Bool, offline: Bool) -> some View { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { if offline { OfflineBanner() }; if cached { WarningBanner(warning: Warning(id: "cache", severity: .information, title: "Dernier état connu", message: "Snapshot local affiché pendant la mise à jour.")) }; ForEach(snapshot.warnings) { WarningBanner(warning: $0) }; if let session = snapshot.activeSession { health(session.runtimeHealth); SessionDetailContent(session: session, compact: true); if session.lifecycle == .reconciliationPending { WarningBanner(warning: Warning(id: "reconciliation", severity: .information, title: "Vérification en cours", message: "Botaplata vérifie encore l'état de cet ordre sur Kraken.")) } } else { EmptyStateView(title: "Aucune session réelle active", message: "Botaplata n'exécute actuellement aucune session Kraken réelle.") } } }
    var header: some View { HStack { VStack(alignment: .leading) { Text("Bonjour").foregroundStyle(.secondary); Text("Botaplata").font(.largeTitle.bold()) }; Spacer(); Button {} label: { Image(systemName: "bell.slash").frame(width: BotaplataTouch.minimum, height: BotaplataTouch.minimum) }.disabled(true).accessibilityLabel("Alertes non fonctionnelles dans cette fondation") } }
    func health(_ monitoring: RuntimeHealthState) -> some View { BotaplataCard { VStack(alignment: .leading, spacing: BotaplataSpacing.sm) { Text(DashboardPresentation.globalMessage(health: monitoring)).font(.headline); HStack { StatusBadge(status: monitoring == .healthy ? .success : .warning, text: monitoring.label); ProviderBadge(provider: .kraken) } } } }
}
#Preview { NavigationStack { DashboardView(summary: PreviewFixtures.dashboardNominalKraken) } }
