import SwiftUI

struct DashboardView: View {
    let content: LoadedContent<RealActiveSnapshot>
    var unreadCount: Int = 0
    var openAlerts: () -> Void = {}
    var refresh: (() async -> Void)? = nil
    init(content: LoadedContent<RealActiveSnapshot>, unreadCount: Int = 0, openAlerts: @escaping () -> Void = {}, refresh: (() async -> Void)? = nil) { self.content = content; self.unreadCount = unreadCount; self.openAlerts = openAlerts; self.refresh = refresh }
    init(summary: DashboardSummary) { self.content = .loaded(RealActiveSnapshot(generatedAt: nil, activeSessionCount: summary.activeSession == nil ? 0 : 1, activeSession: summary.activeSession, warnings: summary.warnings, requestID: nil, serverTime: nil)); self.refresh = nil }
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { header; bodyContent }.padding() }.refreshable { await refresh?() }.background(BotaplataColors.background.ignoresSafeArea()).navigationTitle("Dashboard") }
    @ViewBuilder var bodyContent: some View { switch content { case .idle, .loading: ProgressView("Chargement du dernier état…"); case .error(let message): EmptyStateView(title: "Snapshot indisponible", message: message); case .loaded(let s): snapshot(s, cached: false, offline: false); case .loadedFromCache(let s): snapshot(s, cached: true, offline: false); case .refreshing(let s?): snapshot(s, cached: false, offline: false); case .stale(let s), .offline(let s?): snapshot(s, cached: true, offline: true); case .partial(let s): snapshot(s, cached: false, offline: false); case .refreshing(nil), .offline(nil): EmptyStateView(title: "Snapshot indisponible", message: "Réessayez lorsque la connexion est disponible.") } }
    func snapshot(_ snapshot: RealActiveSnapshot, cached: Bool, offline: Bool) -> some View { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { if offline { OfflineBanner() }; if cached { WarningBanner(warning: Warning(id: "cache", severity: .information, title: "Dernier état connu", message: "Snapshot local affiché pendant la mise à jour.")) }; ForEach(snapshot.warnings) { WarningBanner(warning: $0) }; if let session = snapshot.activeSession { health(session.runtimeHealth); SessionDetailContent(session: session, compact: true, historyStore: nil); if session.lifecycle == .reconciliationPending { WarningBanner(warning: Warning(id: "reconciliation", severity: .information, title: "Vérification en cours", message: "Botaplata vérifie encore l'état de cet ordre sur Kraken.")) } } else { EmptyStateView(title: "Aucune session réelle active", message: "Botaplata n'exécute actuellement aucune session Kraken réelle.") } } }
    var header: some View { HStack { VStack(alignment: .leading) { Text("Bonjour").foregroundStyle(.secondary); Text("Botaplata").font(.largeTitle.bold()) }; Spacer(); Button(action: openAlerts) { ZStack(alignment: .topTrailing) { Image(systemName: "bell").frame(width: BotaplataTouch.minimum, height: BotaplataTouch.minimum); if unreadCount > 0 { Text("\(min(unreadCount, 99))").font(.caption2.bold()).foregroundStyle(.white).padding(5).background(.red, in: Capsule()).offset(x: 6, y: -2) } } }.accessibilityLabel(unreadCount > 0 ? "Alertes, \(unreadCount) non lues" : "Alertes") } }
    func health(_ monitoring: RuntimeHealthState) -> some View { BotaplataCard { VStack(alignment: .leading, spacing: BotaplataSpacing.sm) { Text(DashboardPresentation.globalMessage(health: monitoring)).font(.headline); HStack { StatusBadge(status: monitoring == .healthy ? .success : .warning, text: monitoring.label); ProviderBadge(provider: .kraken) } } } }
}
#Preview { NavigationStack { DashboardView(summary: PreviewFixtures.dashboardNominalKraken) } }
