import Foundation

extension RealActiveSnapshotDTO {
    func mapped(warnings apiWarnings: [APIWarning] = [], requestID: String? = nil, serverTime: Date? = nil) -> RealActiveSnapshot {
        RealActiveSnapshot(generatedAt: generatedAt, activeSessionCount: activeSessionCount, activeSession: activeSession?.mapped(), warnings: apiWarnings.map { Warning(id: $0.code, severity: $0.code == "multiple_active_real_sessions" ? .warning : .information, title: $0.code == "multiple_active_real_sessions" ? "Plusieurs sessions actives" : $0.code, message: $0.message) }, requestID: requestID, serverTime: serverTime)
    }
}

extension Optional where Wrapped == RealFreshnessDTO { func mapped(generatedAt: Date?) -> DataFreshness { guard let f = self else { return DataFreshness(status: .unknown, updatedAt: generatedAt, source: .backend) }; return DataFreshness(status: FreshnessStatus(backend: f.status), updatedAt: f.updatedAt ?? f.snapshotGeneratedAt ?? generatedAt, source: .backend) } }
extension RealOrderDTO { func mapped(currency: String) -> TradingOrderSummary { TradingOrderSummary(id: exchangeOrderID ?? krakenOrderID ?? id ?? UUID().uuidString, side: side ?? "—", status: OrderStatus(backend: status), message: statusLabel ?? OrderStatus(backend: status).label, requestedQuantity: requestedQuantity?.value, executedQuantity: executedQuantity?.value, limitPrice: limitPrice.money(currency), averageExecutionPrice: (averageExecutionPrice ?? averageFillPrice).money(currency), createdAt: createdAt, updatedAt: updatedAt) } }
extension RealFeeAwareDTO { func mapped(currency: String) -> FeeAwareSummary { FeeAwareSummary(executionPrice: executionPrice.money(currency), costBasisPrice: costBasisPrice.money(currency), buyFeeQuote: buyFeeQuote.money(currency), buyFeeRateEffective: buyFeeRateEffective?.value, estimatedSellFeeQuote: estimatedSellFeeQuote.money(currency), estimatedSellFeeRate: estimatedSellFeeRate?.value, estimatedSellFeeSource: estimatedSellFeeSource, breakEvenPrice: breakEvenPrice.money(currency), minimumProfitableExitPrice: minimumProfitableExitPrice.money(currency), minimumNetProfitRate: minimumNetProfitRate?.value, estimatedSlippageRate: estimatedSlippageRate?.value, unrealizedPnLGrossQuote: unrealizedPnlGrossQuote.money(currency), unrealizedPnLNetEstimatedQuote: unrealizedPnlNetEstimatedQuote.money(currency), realizedPnLNetQuote: nil, totalEstimatedCycleFeesQuote: totalCycleFeesEstimatedQuote.money(currency), liquidityRole: liquidityRoleLabel ?? liquidityRole) } }
 
extension FeeAwareSummary { static let empty = FeeAwareSummary(executionPrice: nil, costBasisPrice: nil, buyFeeQuote: nil, buyFeeRateEffective: nil, estimatedSellFeeQuote: nil, estimatedSellFeeRate: nil, estimatedSellFeeSource: nil, breakEvenPrice: nil, minimumProfitableExitPrice: nil, minimumNetProfitRate: nil, estimatedSlippageRate: nil, unrealizedPnLGrossQuote: nil, unrealizedPnLNetEstimatedQuote: nil, realizedPnLNetQuote: nil, totalEstimatedCycleFeesQuote: nil, liquidityRole: nil) }
extension SessionLifecycleState { init(backend: String?) { switch backend { case "waiting_buy": self = .waitingBuy; case "waiting_buy_fill": self = .waitingBuyFill; case "waiting_sell": self = .waitingSell; case "waiting_sell_fill": self = .waitingSellFill; case "reconciliation_pending": self = .reconciliationPending; case "stopped": self = .stopped; case "unknown": self = .unknown; default: self = .unknown } } }
extension RuntimeHealthState { init(backend: String?) { switch backend { case "healthy": self = .healthy; case "degraded": self = .degraded; case "unknown": self = .unknown; default: self = .unknown } } }
extension FreshnessStatus { init(backend: String?) { switch backend { case "fresh": self = .fresh; case "aging": self = .aging; case "stale": self = .stale; case "unknown": self = .unknown; default: self = .unknown } } }
