import SwiftUI

struct AlertsCenterView: View { @Bindable var store: PushNotificationsStore; @Environment(AppRouter.self) private var router; @State private var unreadOnly = false; @State private var confirmAll = false
    var body: some View { List { permissionSection; filterSection; content }.navigationTitle("Alertes").toolbar { Button("Tout marquer comme lu") { confirmAll = true }.disabled(store.unreadCount == 0) }.task { await store.bootstrap() }.refreshable { await store.refreshAll() }.alert("Tout marquer comme lu ?", isPresented: $confirmAll) { Button("Annuler", role: .cancel) {}; Button("Marquer comme lu") { Task { await store.markAllRead() } } } }
    private var permissionSection: some View { Section { if store.permissionStatus == .denied { Text("Notifications refusées\nVous pouvez les réactiver dans les réglages iOS.") } else if store.permissionStatus == .notDetermined { VStack(alignment: .leading) { Text("Recevoir les alertes importantes").font(.headline); Text("Botaplata peut vous prévenir lorsqu'un achat est confirmé, lorsqu'une vente est confirmée ou lorsqu'une vérification dure plus longtemps que prévu."); Button("Activer les notifications") { Task { await store.requestPermission() } } } } } }
    private var filterSection: some View { Section { Picker("Filtre", selection: $unreadOnly) { Text("Toutes").tag(false); Text("Non lues").tag(true) }.pickerStyle(.segmented).onChange(of: unreadOnly) { _, new in store.filters.unreadOnly = new; Task { await store.refreshAll() } } } }
    @ViewBuilder private var content: some View { switch store.notifications { case .idle, .loading: ProgressView("Chargement des alertes…"); case .error: EmptyStateView(title: "Impossible de charger les alertes", message: "Vérifiez votre connexion puis réessayez."); case .offline(let items?): Text("Connexion momentanément indisponible. Dernier état connu affiché.").font(.footnote).foregroundStyle(.secondary); rows(items); case .loaded(let items), .loadedFromCache(let items), .refreshing(let items?), .partial(let items), .stale(let items): rows(items); case .refreshing(nil), .offline(nil): EmptyStateView(title: "Impossible de charger les alertes", message: "Vérifiez votre connexion puis réessayez.") } }
    @ViewBuilder private func rows(_ items: [RealNotificationItem]) -> some View { let visible = unreadOnly ? items.filter { !$0.isRead } : items; if visible.isEmpty { EmptyStateView(title: unreadOnly ? "Tout est lu" : "Aucune alerte", message: "Les événements importants de Botaplata apparaîtront ici.") } else { ForEach(Dictionary(grouping: visible, by: dayTitle).keys.sorted(by: >), id: \.self) { key in Section(key) { ForEach(Dictionary(grouping: visible, by: dayTitle)[key] ?? []) { item in Button { Task { await store.markRead(item); if let target = item.navigationTarget { router.route(to: target) } } } label: { NotificationRow(item: item) }.buttonStyle(.plain) } } } } }
    private func dayTitle(_ item: RealNotificationItem) -> String { Calendar.current.isDateInToday(item.createdAt) ? "Aujourd'hui" : (Calendar.current.isDateInYesterday(item.createdAt) ? "Hier" : item.createdAt.formatted(date: .abbreviated, time: .omitted)) }
}
struct NotificationRow: View { let item: RealNotificationItem; var body: some View { HStack(alignment: .top) { Circle().fill(item.isRead ? .clear : BotaplataColors.accent).frame(width: 8, height: 8).padding(.top, 7); VStack(alignment: .leading, spacing: 5) { HStack { Text(item.title).font(.headline); Spacer(); Text(item.severity.label).font(.caption).padding(5).background(.thinMaterial, in: Capsule()) }; Text(item.message).foregroundStyle(.secondary); Text([item.symbol, relative].compactMap { $0 }.joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) } } .accessibilityElement(children: .ignore).accessibilityLabel("\(item.title), \(item.severity.label), \(item.symbol?.replacingOccurrences(of: "/", with: " ") ?? ""), \(relative), \(item.isRead ? "lu" : "non lu")") }
    private var relative: String { let f = RelativeDateTimeFormatter(); f.locale = Locale(identifier: "fr_FR"); f.unitsStyle = .full; return f.localizedString(for: item.createdAt, relativeTo: Date()) }
}

struct PushPreferencesView: View { @Bindable var store: PushNotificationsStore; var body: some View { List { switch store.preferences { case .idle, .loading: ProgressView("Chargement…"); case .error: EmptyStateView(title: "Préférences indisponibles", message: "Réessayez plus tard."); case .loaded(let p), .loadedFromCache(let p), .refreshing(let p?), .offline(let p?), .partial(let p), .stale(let p): Section("Trading réel") { ForEach(p.categories) { item in PreferenceRow(item: item, toggle: { enabled in Task { await store.updatePreference(item, enabled: enabled) } }) } }; case .refreshing(nil), .offline(nil): EmptyStateView(title: "Préférences indisponibles", message: "Réessayez plus tard.") } }.navigationTitle("Préférences d'alertes").task { await store.bootstrap() } } }
struct PreferenceRow: View { let item: PushPreferenceItem; let toggle: (Bool) -> Void; var body: some View { if item.mandatory { LabeledContent(label(for: item.eventType), value: "Toujours actif") } else { Toggle(isOn: Binding(get: { item.enabled }, set: toggle)) { Text(label(for: item.eventType)) } } }
    private func label(for event: String) -> String { ["real_buy_filled":"Achat confirmé", "real_sell_submitted":"Ordre de vente envoyé", "real_sell_filled":"Vente confirmée", "real_reconciliation_prolonged":"Vérification prolongée", "real_monitoring_degraded":"Surveillance perturbée", "real_order_rejected":"Ordre rejeté", "real_protection_triggered":"Protection critique", "real_critical_error":"Erreur critique"][event] ?? "Alerte importante" } }
#Preview("Alertes nominales") { NavigationStack { AlertsCenterView(store: .preview()) }.environment(AppRouter()) }
#Preview("Préférences push") { NavigationStack { PushPreferencesView(store: .preview()) } }
