import SwiftUI

enum AlertsFilter: String, CaseIterable, Identifiable { case all, unread, critical, sessions, system; var id: String { rawValue }; var title: String { switch self { case .all: "Toutes"; case .unread: "Non lues"; case .critical: "Critiques"; case .sessions: "Sessions"; case .system: "Système" } } }
struct AlertPresentation: Equatable { let severityLabel: String; let status: BadgeStatus; let icon: String; let hasDestination: Bool
    static func make(from item: RealNotificationItem) -> Self { let status: BadgeStatus = switch item.severity { case .info: .active; case .watch, .warning: .warning; case .critical: .danger }; let icon = switch item.severity { case .info: "info.circle"; case .watch, .warning: "exclamationmark.triangle"; case .critical: "exclamationmark.octagon" }; return .init(severityLabel: item.severity.label, status: status, icon: icon, hasDestination: item.navigationTarget?.sessionID != nil) }
    static func filtered(_ items: [RealNotificationItem], filter: AlertsFilter) -> [RealNotificationItem] { switch filter { case .all: items; case .unread: items.filter { !$0.isRead }; case .critical: items.filter { $0.severity == .critical }; case .sessions: items.filter { $0.sessionID != nil }; case .system: items.filter { $0.sessionID == nil } } }
}

struct AlertsCenterView: View { @Bindable var store: PushNotificationsStore; @Environment(AppRouter.self) private var router; @State private var filter: AlertsFilter = .all; @State private var confirmAll = false
    var body: some View { ZStack { PremiumBackground(); ScrollView { LazyVStack(alignment: .leading, spacing: BotaplataSpacing.md) { header; permissionSection; content } .padding(BotaplataSpacing.md) }.refreshable { await store.refreshAll() } }.navigationTitle("Alertes").task { await store.bootstrap() }.alert("Tout marquer comme lu ?", isPresented: $confirmAll) { Button("Annuler", role: .cancel) {}; Button("Marquer comme lu") { Task { await store.markAllRead() } } } }
    private var header: some View { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { HStack(alignment: .firstTextBaseline) { Text("Alertes").font(BotaplataTypography.largeTitle).foregroundStyle(BotaplataColors.textPrimary); Spacer(); if store.unreadCount > 0 { Button("Tout marquer comme lu") { confirmAll = true }.font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.primaryMint).accessibilityLabel("Marquer toutes les alertes comme lues") } }; ScrollView(.horizontal, showsIndicators: false) { HStack { ForEach(AlertsFilter.allCases) { item in Button { filter = item } label: { FilterPill(title: item.title, isSelected: filter == item) }.buttonStyle(.plain).accessibilityLabel("Filtre Alertes \(item.title)") } } }; Text(store.unreadCount == 0 ? "Aucune alerte non lue" : "\(store.unreadCount) alerte\(store.unreadCount > 1 ? "s" : "") non lue\(store.unreadCount > 1 ? "s" : "")").font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.textSecondary) } }
    @ViewBuilder private var permissionSection: some View { if store.permissionStatus == .denied { PremiumCard(variant: .warning) { Text("Notifications refusées").font(BotaplataTypography.cardTitle); Text("Vous pouvez les réactiver dans les réglages iOS.").foregroundStyle(BotaplataColors.textSecondary) } } else if store.permissionStatus == .notDetermined { PremiumCard { Text("Recevoir les alertes importantes").font(BotaplataTypography.cardTitle); Text("Botaplata peut vous prévenir lorsqu'une situation réelle mérite votre attention.").foregroundStyle(BotaplataColors.textSecondary); PremiumSecondaryButton(title: "Activer les notifications") { Task { await store.requestPermission() } } } } }
    @ViewBuilder private var content: some View { switch store.notifications { case .idle, .loading: ForEach(0..<3, id: \.self) { _ in PremiumSkeletonCard() }; case .error: PremiumErrorState(title: "Impossible de charger les alertes", message: "Vérifiez la connexion au serveur Botaplata."); case .offline(let items?): PremiumOfflineBanner(); Text("Dernier état enregistré sur cet iPhone.").font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.textMuted); rows(items); case .loaded(let items), .loadedFromCache(let items), .refreshing(let items?), .partial(let items), .stale(let items): rows(items); case .refreshing(nil), .offline(nil): PremiumErrorState(title: "Impossible de charger les alertes", message: "Vérifiez la connexion au serveur Botaplata.") } }
    @ViewBuilder private func rows(_ items: [RealNotificationItem]) -> some View { let visible = AlertPresentation.filtered(items, filter: filter); if visible.isEmpty { PremiumEmptyState(title: filter == .unread ? "Tout est à jour" : "Aucune alerte", message: filter == .unread ? "Vous avez consulté toutes les alertes." : "Tout fonctionne normalement pour le moment.", systemImage: "bell") } else { ForEach(HistoryPresentation.groupNotifications(visible), id: \.title) { group in TimelineDateHeader(title: group.title); ForEach(group.items) { item in Button { Task { await store.markRead(item); if let target = item.navigationTarget { router.route(to: target) } } } label: { PremiumAlertCard(item: item) }.buttonStyle(.plain) } } } }
}

struct PremiumAlertCard: View { let item: RealNotificationItem; private var p: AlertPresentation { .make(from: item) }
    var body: some View { PremiumCard(variant: item.isRead ? .normal : (item.severity == .critical ? .danger : .elevated)) { VStack(alignment: .leading, spacing: BotaplataSpacing.sm) { HStack { SeverityPill(item: item); if !item.isRead { UnreadIndicator() }; Spacer(); Text(relative).font(.caption).foregroundStyle(BotaplataColors.textMuted) }; Text(item.title).font(BotaplataTypography.cardTitle).foregroundStyle(BotaplataColors.textPrimary); Text(item.message).font(BotaplataTypography.body).foregroundStyle(BotaplataColors.textSecondary); HStack { if let symbol = item.symbol { Text(symbol) }; if let provider = item.provider { Text(provider.capitalized) } }.font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.textMuted); if p.hasDestination { Label("Voir la session", systemImage: "arrow.right.circle").font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.primaryMint) } } }.accessibilityElement(children: .ignore).accessibilityLabel("Alerte \(p.severityLabel), \(item.isRead ? "lue" : "non lue"). \(item.title). \(item.symbol?.replacingOccurrences(of: "/", with: " ") ?? ""). \(relative). \(p.hasDestination ? "Ouvre la session." : "Aucune destination secondaire.")") }
    private var relative: String { let f = RelativeDateTimeFormatter(); f.locale = Locale(identifier: "fr_FR"); f.unitsStyle = .abbreviated; return f.localizedString(for: item.createdAt, relativeTo: Date()) }
}
struct SeverityPill: View { let item: RealNotificationItem; var body: some View { StatusPill(status: AlertPresentation.make(from: item).status, text: item.severity.label) } }
struct UnreadIndicator: View { var body: some View { HStack(spacing: 4) { Circle().fill(BotaplataColors.primaryMint).frame(width: 8, height: 8); Text("Non lue") }.font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.primaryMint).accessibilityLabel("Non lue") } }

extension HistoryPresentation { static func groupNotifications(_ items: [RealNotificationItem]) -> [(title: String, items: [RealNotificationItem])] { Dictionary(grouping: items) { Calendar.current.isDateInToday($0.createdAt) ? "Aujourd'hui" : (Calendar.current.isDateInYesterday($0.createdAt) ? "Hier" : fullDate($0.createdAt).components(separatedBy: " à ").first ?? fullDate($0.createdAt)) }.map { ($0.key, $0.value) }.sorted { $0.items.first?.createdAt ?? .distantPast > $1.items.first?.createdAt ?? .distantPast } } }

struct PushPreferencesView: View {
    @Bindable var store: PushNotificationsStore
    var body: some View {
        ZStack { PremiumBackground(); ScrollView { LazyVStack(alignment: .leading, spacing: BotaplataSpacing.md) { header; content }.padding(BotaplataSpacing.md) } }
            .navigationTitle("Préférences")
            .task { await store.bootstrap() }
            .overlay(alignment: .bottom) { if let message = store.preferenceMessage { Text(message).font(.footnote).padding().background(.thinMaterial, in: Capsule()).padding() } }
    }
    private var header: some View { PremiumCard(variant: .hero) { VStack(alignment: .leading, spacing: 8) { Text("Notifications Botaplata").font(BotaplataTypography.largeTitle); Text("Choisissez les alertes serveur que cet iPhone doit recevoir. La permission iOS reste distincte de ces préférences.").foregroundStyle(BotaplataColors.textSecondary) } } }
    @ViewBuilder private var content: some View { switch store.preferences { case .idle, .loading: PremiumSkeletonCard(); case .error: PremiumErrorState(title: "Préférences indisponibles", message: "Réessayez plus tard."); case .loaded(let p), .loadedFromCache(let p), .refreshing(let p?), .offline(let p?), .partial(let p), .stale(let p): if p.categories.isEmpty { PremiumEmptyState(title: "Aucune préférence", message: "Le serveur Botaplata n’a fourni aucune préférence modifiable.") } else { ForEach(p.categories) { item in PremiumPreferenceCard(item: item, isSaving: store.savingPreferenceEventTypes.contains(item.eventType), toggle: { enabled in Task { await store.updatePreference(item, enabled: enabled) } }) } }; case .refreshing(nil), .offline(nil): PremiumErrorState(title: "Préférences indisponibles", message: "Vérifiez la connexion au serveur Botaplata.") } }
}

struct PremiumPreferenceCard: View {
    let item: PushPreferenceItem
    let isSaving: Bool
    let toggle: (Bool) -> Void
    var body: some View { PremiumCard { HStack(alignment: .center, spacing: BotaplataSpacing.md) { IconBadge(symbol: ProfilePresentation.preferenceSymbol(item.eventType), label: ProfilePresentation.preferenceTitle(item.eventType), color: item.enabled ? BotaplataColors.primaryMint : BotaplataColors.textMuted); VStack(alignment: .leading, spacing: 4) { Text(ProfilePresentation.preferenceTitle(item.eventType)).font(BotaplataTypography.cardTitle); Text(ProfilePresentation.preferenceDetail(item.eventType)).font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.textSecondary); if item.mandatory { Text("Toujours actif").font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.primaryMint) } }; Spacer(); if isSaving { ProgressView().tint(BotaplataColors.primaryMint) } else if item.mandatory { StatusPill(status: .active, text: "Obligatoire") } else { Toggle("", isOn: Binding(get: { item.enabled }, set: toggle)).labelsHidden().tint(BotaplataColors.primaryTeal) } } }.accessibilityElement(children: .combine) }
}


#Preview("Alertes nominales") { NavigationStack { AlertsCenterView(store: PushNotificationsStore.preview()) } }
#Preview("Alerte critical") { PremiumAlertCard(item: PreviewFixtures.notifications[1]).padding().background(BotaplataColors.background) }
#Preview("Alerte sans destination") { PremiumAlertCard(item: RealNotificationItem(id: "fixture-system", eventType: "device_revoked", severity: .critical, title: "Appareil révoqué", message: "Cet appareil doit être vérifié.", createdAt: Date(), isRead: false, sessionID: nil, symbol: nil, provider: nil, navigationTarget: nil, money: nil)).padding().background(BotaplataColors.background) }
