import XCTest
@testable import BotaplataApp

final class RealSessionHistoryDTOTests: XCTestCase {
    func testTimelineOrdersDecisionsAndChartDTOsPreserveDecimalAndNullSemantics() throws {
        let timeline = try JSONCoding.decoder.decode(TimelinePageDTO.self, from: Data(#"{"items":[{"id":"e1","occurred_at":"2026-07-13T13:18:00Z","type":"buy_filled","severity":"success","title":"Achat confirmé par Kraken","message":"L'achat a été confirmé par Kraken.","related_order_id":"o1","related_position_id":null,"money":{"amount_quote":"77.74","currency":"USDC"}}],"pagination":{"page":1,"page_size":50,"total":1,"has_more":false}}"#.utf8)).mapped(warnings: [], serverTime: nil)
        XCTAssertEqual(timeline.items[0].type, .buyFilled); XCTAssertEqual(timeline.items[0].money?.amountQuote?.value, Decimal(string: "77.74")); XCTAssertFalse(timeline.pagination.hasMore)
        let orders = try JSONCoding.decoder.decode(OrdersPageDTO.self, from: Data(#"{"items":[{"id":"o1","side":"buy","order_type":"limit","status":"reconciliation_required","status_label":"Vérification en cours","provider":"kraken","symbol":"SOL/USDC","requested_quantity":"10.29071263","executed_quantity":"10.29071263","average_fill_price":"77.74","executed_quote_amount":"799.99","fees_quote":"6.40","created_at":"2026-07-13T13:18:00Z","realized_pnl_quote":null,"realized_pnl_net_quote":null}],"pagination":{"page":1,"page_size":50,"total":1,"has_more":false}}"#.utf8)).mapped(warnings: [], serverTime: nil)
        XCTAssertEqual(orders.items[0].status, .reconciliationRequired); XCTAssertNil(orders.items[0].realizedPnLNetQuote); XCTAssertEqual(orders.items[0].feesQuote?.value, Decimal(string: "6.40"))
        let decisions = try JSONCoding.decoder.decode(DecisionsPageDTO.self, from: Data(#"{"items":[{"id":"d1","created_at":"2026-07-13T13:18:00Z","decision":"wait","decision_label":"Attente","score":"2.5","score_min":"4","price":"77.74","controller":"real","blockers":["Signal incomplet"],"buy_conditions":["Liquidité"],"sell_conditions":[],"advice":["Attendre"],"summary_title":"Botaplata continue d'attendre.","summary_message":"Les conditions d'achat ne sont pas encore réunies."}],"pagination":{"page":1,"page_size":50,"total":1,"has_more":false}}"#.utf8)).mapped(warnings: [], serverTime: nil)
        XCTAssertEqual(decisions.items[0].summaryTitle, "Botaplata continue d'attendre."); XCTAssertEqual(decisions.items[0].blockers, ["Signal incomplet"])
        let chart = try JSONCoding.decoder.decode(SessionChartDTO.self, from: Data(#"{"session_id":"s1","symbol":"SOLUSDC","display_symbol":"SOL/USDC","quote_asset":"USDC","timeframe":"1m","points":[],"markers":[{"id":"m1","timestamp":"2026-07-13T13:18:00Z","type":"buy","label":"Achat confirmé","price":"77.74","quantity":"10.29071263","quote_amount":"799.99"}],"levels":{"execution_price":"77.74","cost_basis_price":"78.36","break_even_price":"78.98","minimum_profitable_exit_price":"79.10"}}"#.utf8)).mapped(warnings: [APIWarning(code: "chart_price_series_unavailable", message: "technical")], serverTime: nil)
        XCTAssertTrue(chart.points.isEmpty); XCTAssertEqual(chart.markers[0].type, .buy); XCTAssertEqual(chart.levels.breakEvenPrice?.value, Decimal(string: "78.98")); XCTAssertEqual(chart.warnings[0].id, "chart_price_series_unavailable")
    }
}
