import SwiftUI

struct PremiumBackground: View {
    var body: some View {
        ZStack {
            BotaplataGradients.appBackground
            Circle().fill(BotaplataColors.primaryTeal.opacity(0.18)).frame(width: 260, height: 260).blur(radius: 42).offset(x: 150, y: -260)
            Circle().fill(BotaplataColors.backgroundNavy.opacity(0.38)).frame(width: 340, height: 340).blur(radius: 54).offset(x: -170, y: 230)
        }
        .ignoresSafeArea()
        .accessibilityHidden(true)
    }
}

enum PremiumCardVariant { case normal, elevated, success, warning, danger, hero
    var gradient: LinearGradient { switch self { case .normal: LinearGradient(colors: [BotaplataColors.cardGlass, BotaplataColors.backgroundElevated.opacity(0.56)], startPoint: .topLeading, endPoint: .bottomTrailing); case .elevated: LinearGradient(colors: [Color.white.opacity(0.11), BotaplataColors.backgroundElevated.opacity(0.76)], startPoint: .topLeading, endPoint: .bottomTrailing); case .success: BotaplataGradients.cardTeal; case .warning: BotaplataGradients.cardWarning; case .danger: BotaplataGradients.cardDanger; case .hero: BotaplataGradients.cardHero } }
    var glow: Color { switch self { case .success, .hero: BotaplataShadow.glowTeal; case .warning: BotaplataColors.warning.opacity(0.14); case .danger: BotaplataShadow.dangerGlow; default: BotaplataShadow.cardColor } }
}

struct PremiumCard<Content: View>: View {
    let variant: PremiumCardVariant
    @ViewBuilder var content: Content
    init(variant: PremiumCardVariant = .normal, @ViewBuilder content: () -> Content) { self.variant = variant; self.content = content() }
    var body: some View { content.padding(BotaplataSpacing.md).frame(maxWidth: .infinity, alignment: .leading).background(variant.gradient, in: RoundedRectangle(cornerRadius: BotaplataRadius.lg, style: .continuous)).overlay(alignment: .topLeading) { RoundedRectangle(cornerRadius: BotaplataRadius.lg, style: .continuous).stroke(BotaplataColors.cardBorder, lineWidth: BotaplataBorder.subtle) }.shadow(color: variant.glow, radius: BotaplataShadow.radius, x: 0, y: BotaplataShadow.y) }
}

struct GlassCard<Content: View>: View { @ViewBuilder var content: Content; var body: some View { PremiumCard(variant: .elevated) { content } } }
struct BotaplataCard<Content: View>: View { @ViewBuilder var content: Content; var body: some View { PremiumCard { content } } }

struct MetricCard: View {
    let title: String; let value: String; let footnote: String?; let variant: PremiumCardVariant
    init(title: String, value: String, footnote: String? = nil, variant: PremiumCardVariant = .normal) { self.title = title; self.value = value; self.footnote = footnote; self.variant = variant }
    var body: some View { PremiumCard(variant: variant) { VStack(alignment: .leading, spacing: BotaplataSpacing.xs) { Text(title).font(BotaplataTypography.caption).foregroundStyle(BotaplataColors.textSecondary); Text(value).font(BotaplataTypography.metricValue).foregroundStyle(BotaplataColors.textPrimary).minimumScaleFactor(0.75); if let footnote { Text(footnote).font(.caption).foregroundStyle(BotaplataColors.textMuted) } } }.accessibilityElement(children: .combine) }
}

enum BadgeStatus { case active, waiting, success, warning, danger, neutral; var color: Color { switch self { case .active: BotaplataColors.primaryTeal; case .waiting: BotaplataColors.accentCyan; case .success: BotaplataColors.success; case .warning: BotaplataColors.warning; case .danger: BotaplataColors.danger; case .neutral: BotaplataColors.neutral } }; var icon: String { switch self { case .active: "dot.radiowaves.left.and.right"; case .waiting: "clock"; case .success: BotaplataSymbol.success; case .warning: BotaplataSymbol.warning; case .danger: BotaplataSymbol.critical; case .neutral: "circle" } } }
struct StatusPill: View { let status: BadgeStatus; let text: String; var accessibilityText: String? = nil; var body: some View { Label(text, systemImage: status.icon).font(.caption.weight(.semibold)).lineLimit(1).padding(.horizontal, 11).padding(.vertical, 7).foregroundStyle(status.color).background(status.color.opacity(0.16), in: Capsule()).overlay(Capsule().stroke(status.color.opacity(0.34), lineWidth: 1)).accessibilityElement(children: .ignore).accessibilityLabel(accessibilityText ?? text) } }
struct StatusBadge: View { let status: BadgeStatus; let text: String; var body: some View { StatusPill(status: status, text: text) } }
struct FilterPill: View { let title: String; var isSelected: Bool; var body: some View { Text(title).font(.caption.weight(.semibold)).padding(.horizontal, 14).padding(.vertical, 8).foregroundStyle(isSelected ? BotaplataColors.backgroundDeep : BotaplataColors.textSecondary).background(isSelected ? AnyShapeStyle(BotaplataGradients.buttonPrimary) : AnyShapeStyle(BotaplataColors.cardGlass), in: Capsule()).overlay(Capsule().stroke(BotaplataColors.cardBorder, lineWidth: 1)).accessibilityAddTraits(isSelected ? .isSelected : []) } }
struct LiveBadge: View { var body: some View { StatusPill(status: .active, text: "LIVE", accessibilityText: "LIVE, session en cours") } }
enum SeverityLevel { case attention, critical, success; var status: BadgeStatus { self == .critical ? .danger : self == .success ? .success : .warning }; var text: String { self == .critical ? "Critique" : self == .success ? "En cours" : "Attention" }; var accessibility: String { self == .critical ? "Critique, protection déclenchée" : self == .success ? "En cours, état opérationnel" : "Attention, surveillance perturbée" } }
struct SeverityBadge: View { let level: SeverityLevel; var body: some View { StatusPill(status: level.status, text: level.text, accessibilityText: level.accessibility) } }
struct IconBadge: View { let symbol: String; let label: String; let color: Color; var body: some View { Label(label, systemImage: symbol).font(.caption.weight(.semibold)).padding(.horizontal, 10).padding(.vertical, 7).foregroundStyle(color).background(color.opacity(0.14), in: Capsule()).accessibilityElement(children: .combine) } }
struct ProviderBadge: View { let provider: TradingProvider; var body: some View { StatusPill(status: provider == .kraken ? .active : provider == .binanceLegacy ? .neutral : .warning, text: provider.displayName, accessibilityText: "Fournisseur \(provider.displayName)") } }
struct FreshnessBadge: View { let freshness: DataFreshness; var body: some View { StatusPill(status: status, text: label) }; var status: BadgeStatus { switch freshness.status { case .fresh: .success; case .aging: .waiting; case .stale: .warning; case .cached: .neutral; case .unknown: .neutral } }; var label: String { switch freshness.status { case .fresh: "Données fraîches"; case .aging: "À surveiller"; case .stale: "Attention"; case .cached: "Dernier état connu"; case .unknown: "État inconnu" } } }

struct PremiumPrimaryButton: View { let title: String; var isLoading = false; var action: () -> Void; var body: some View { Button(action: action) { HStack { if isLoading { ProgressView().tint(BotaplataColors.backgroundDeep) }; Text(isLoading ? "Chargement…" : title).font(.headline) }.frame(maxWidth: .infinity, minHeight: BotaplataTouch.minimum) }.buttonStyle(PremiumPrimaryButtonStyle()) } }
struct PremiumSecondaryButton: View { let title: String; var action: () -> Void; var body: some View { Button(title, action: action).buttonStyle(PremiumSecondaryButtonStyle()) } }
struct PremiumDangerButton: View { let title: String; var action: () -> Void; var body: some View { Button(title, action: action).buttonStyle(PremiumDangerButtonStyle()) } }
struct IconTextButton: View { let title: String; let systemImage: String; var action: () -> Void; var body: some View { Button(action: action) { Label(title, systemImage: systemImage).frame(maxWidth: .infinity, minHeight: BotaplataTouch.minimum) }.buttonStyle(PremiumSecondaryButtonStyle()) } }
struct PremiumPrimaryButtonStyle: ButtonStyle { func makeBody(configuration: Configuration) -> some View { configuration.label.padding(.horizontal, BotaplataSpacing.md).foregroundStyle(BotaplataColors.backgroundDeep).background(BotaplataGradients.buttonPrimary.opacity(configuration.isPressed ? 0.78 : 1), in: RoundedRectangle(cornerRadius: BotaplataRadius.md, style: .continuous)).opacity(configuration.isPressed ? 0.88 : 1) } }
struct PremiumSecondaryButtonStyle: ButtonStyle { func makeBody(configuration: Configuration) -> some View { configuration.label.font(.headline).padding(.horizontal, BotaplataSpacing.md).frame(minHeight: BotaplataTouch.minimum).foregroundStyle(BotaplataColors.textPrimary).background(BotaplataColors.cardGlass.opacity(configuration.isPressed ? 0.55 : 1), in: RoundedRectangle(cornerRadius: BotaplataRadius.md, style: .continuous)).overlay(RoundedRectangle(cornerRadius: BotaplataRadius.md, style: .continuous).stroke(BotaplataColors.cardBorder, lineWidth: 1)) } }
struct PremiumDangerButtonStyle: ButtonStyle { func makeBody(configuration: Configuration) -> some View { configuration.label.font(.headline).padding(.horizontal, BotaplataSpacing.md).frame(maxWidth: .infinity, minHeight: BotaplataTouch.minimum).foregroundStyle(.white).background(BotaplataColors.danger.opacity(configuration.isPressed ? 0.70 : 0.92), in: RoundedRectangle(cornerRadius: BotaplataRadius.md, style: .continuous)) } }

struct MoneyValue: View { let amount: MoneyAmount?; var body: some View { Text(FinancialFormatters.money(amount)).font(BotaplataTypography.monoValue) } }
struct PercentageValue: View { let value: Decimal?; var body: some View { Text(FinancialFormatters.percent(value)).font(BotaplataTypography.monoValue) } }
struct WarningBanner: View { let warning: Warning; var body: some View { PremiumCard(variant: warning.severity == .critical ? .danger : .warning) { Label { VStack(alignment: .leading, spacing: 3) { Text(warning.title).font(BotaplataTypography.cardTitle); Text(warning.message).font(.subheadline).foregroundStyle(BotaplataColors.textSecondary) } } icon: { Image(systemName: warning.severity == .critical ? BotaplataSymbol.critical : BotaplataSymbol.warning) } }.accessibilityElement(children: .combine) }; }
struct OfflineBanner: View { var body: some View { PremiumOfflineBanner() } }
struct PremiumOfflineBanner: View { var body: some View { WarningBanner(warning: Warning(id: "offline", severity: .warning, title: "Connexion momentanément indisponible", message: "Dernier état connu affiché.")) } }
struct EmptyStateView: View { let title: String; let message: String; var body: some View { PremiumEmptyState(title: title, message: message) } }
struct PremiumEmptyState: View { let title: String; let message: String; var systemImage = "tray"; var body: some View { PremiumCard { Label(title, systemImage: systemImage).font(BotaplataTypography.cardTitle); Text(message).font(BotaplataTypography.body).foregroundStyle(BotaplataColors.textSecondary) }.accessibilityElement(children: .combine) } }
struct ErrorStateView: View { let title: String; let message: String; var body: some View { PremiumErrorState(title: title, message: message) } }
struct PremiumErrorState: View { let title: String; let message: String; var body: some View { PremiumCard(variant: .danger) { Label(title, systemImage: BotaplataSymbol.critical).font(BotaplataTypography.cardTitle); Text(message).foregroundStyle(BotaplataColors.textSecondary) }.accessibilityElement(children: .combine) } }
struct LoadingStateView: View { let title: String; let message: String; var body: some View { PremiumLoadingState(title: title, message: message) } }
struct PremiumLoadingState: View { let title: String; let message: String; var body: some View { PremiumCard { HStack(spacing: BotaplataSpacing.md) { ProgressView().tint(BotaplataColors.primaryMint); VStack(alignment: .leading, spacing: 4) { Text(title).font(BotaplataTypography.cardTitle); Text(message).foregroundStyle(BotaplataColors.textSecondary) } } }.accessibilityElement(children: .combine) } }
struct PremiumSkeletonCard: View { @Environment(\.accessibilityReduceMotion) private var reduceMotion; @State private var highlighted = false; var body: some View { PremiumCard { VStack(alignment: .leading, spacing: BotaplataSpacing.sm) { Capsule().fill(BotaplataColors.cardBorder).frame(width: 140, height: 14); Capsule().fill(BotaplataColors.cardBorder.opacity(0.7)).frame(height: 24); Capsule().fill(BotaplataColors.cardBorder.opacity(0.55)).frame(width: 220, height: 12) }.opacity(highlighted ? 0.55 : 1) }.onAppear { guard !reduceMotion else { return }; withAnimation(.easeInOut(duration: 1.1).repeatForever(autoreverses: true)) { highlighted = true } }.accessibilityLabel("Données en préparation") } }
struct SectionHeader: View { let title: String; let subtitle: String?; var body: some View { VStack(alignment: .leading, spacing: 3) { Text(title).font(BotaplataTypography.sectionTitle); if let subtitle { Text(subtitle).font(.subheadline).foregroundStyle(BotaplataColors.textSecondary) } }.frame(maxWidth: .infinity, alignment: .leading) } }
struct MetricTile: View { let title: String; let value: String; let footnote: String?; var body: some View { MetricCard(title: title, value: value, footnote: footnote) } }

#Preview("Premium Design System V2") { ZStack { PremiumBackground(); ScrollView { VStack(alignment: .leading, spacing: BotaplataSpacing.md) { Text("Botaplata Premium").font(BotaplataTypography.largeTitle).foregroundStyle(BotaplataColors.textPrimary); PremiumCard(variant: .hero) { VStack(alignment: .leading) { LiveBadge(); Text("Session active").font(BotaplataTypography.cardTitle); Text("Botaplata surveille le marché.").foregroundStyle(BotaplataColors.textSecondary) } }; MetricCard(title: "Valeur estimée", value: "1 245,80 €", footnote: "Fixture locale", variant: .success); HStack { StatusPill(status: .active, text: "En cours"); SeverityBadge(level: .attention); SeverityBadge(level: .critical) }; HStack { FilterPill(title: "Toutes", isSelected: true); FilterPill(title: "À surveiller", isSelected: false) }; PremiumPrimaryButton(title: "Continuer", action: {}); PremiumSecondaryButton(title: "Voir le détail", action: {}); PremiumDangerButton(title: "Révoquer l'accès", action: {}); PremiumOfflineBanner(); PremiumEmptyState(title: "Aucune session réelle", message: "Les sessions Kraken apparaîtront ici lorsqu’elles seront disponibles."); PremiumLoadingState(title: "Données en préparation", message: "Botaplata prépare l’historique nécessaire."); PremiumSkeletonCard() }.padding() } } }
