import SwiftUI

struct BotaplataCard<Content: View>: View { @ViewBuilder var content: Content; var body: some View { content.padding(BotaplataSpacing.md).frame(maxWidth: .infinity, alignment: .leading).background(.regularMaterial, in: RoundedRectangle(cornerRadius: BotaplataRadius.lg)).overlay(RoundedRectangle(cornerRadius: BotaplataRadius.lg).stroke(BotaplataColors.accent.opacity(0.18), lineWidth: BotaplataBorder.subtle)) } }
enum BadgeStatus { case active, waiting, success, warning, danger, neutral; var color: Color { switch self { case .active: BotaplataColors.accent; case .waiting: .blue; case .success: BotaplataColors.success; case .warning: BotaplataColors.warning; case .danger: BotaplataColors.danger; case .neutral: BotaplataColors.neutral } }; var icon: String { switch self { case .active: "dot.radiowaves.left.and.right"; case .waiting: "clock"; case .success: "checkmark.circle"; case .warning: "exclamationmark.triangle"; case .danger: "xmark.octagon"; case .neutral: "circle" } } }
struct StatusBadge: View { let status: BadgeStatus; let text: String; var body: some View { Label(text, systemImage: status.icon).font(.caption.weight(.semibold)).padding(.horizontal, 10).padding(.vertical, 6).foregroundStyle(status.color).background(status.color.opacity(0.14), in: Capsule()).accessibilityLabel(Text(text)) } }
struct ProviderBadge: View { let provider: TradingProvider; var body: some View { StatusBadge(status: provider == .kraken ? .active : provider == .binanceLegacy ? .neutral : .warning, text: provider.displayName) } }
struct FreshnessBadge: View { let freshness: DataFreshness; var body: some View { StatusBadge(status: status, text: label) } var status: BadgeStatus { switch freshness.status { case .fresh: .success; case .aging: .waiting; case .stale: .warning; case .cached: .neutral; case .unknown: .neutral } } var label: String { switch freshness.status { case .fresh: "Données fraîches"; case .aging: "Données vieillissantes"; case .stale: "Données obsolètes"; case .cached: "Dernier cache"; case .unknown: "Fraîcheur inconnue" } } }
struct MoneyValue: View { let amount: MoneyAmount?; var body: some View { Text(FinancialFormatters.money(amount)).monospacedDigit().font(.headline) } }
struct PercentageValue: View { let value: Decimal?; var body: some View { Text(FinancialFormatters.percent(value)).monospacedDigit().font(.headline) } }
struct WarningBanner: View { let warning: Warning; var body: some View { Label { VStack(alignment: .leading) { Text(warning.title).bold(); Text(warning.message).font(.subheadline) } } icon: { Image(systemName: warning.severity == .critical ? "xmark.octagon" : "exclamationmark.triangle") }.padding().background(color.opacity(0.16), in: RoundedRectangle(cornerRadius: BotaplataRadius.md)) } var color: Color { warning.severity == .critical ? BotaplataColors.danger : BotaplataColors.warning } }
struct OfflineBanner: View { var body: some View { WarningBanner(warning: Warning(id: "offline", severity: .warning, title: "Hors ligne", message: "Connexion momentanément indisponible. Dernier état connu affiché.")) } }
struct EmptyStateView: View { let title: String; let message: String; var body: some View { BotaplataCard { Label(title, systemImage: "tray").font(.headline); Text(message).foregroundStyle(.secondary) } } }
struct ErrorStateView: View { let title: String; let message: String; var body: some View { BotaplataCard { Label(title, systemImage: "exclamationmark.octagon").font(.headline).foregroundStyle(BotaplataColors.danger); Text(message).foregroundStyle(.secondary) } } }
struct LoadingStateView: View { let title: String; let message: String; var body: some View { BotaplataCard { HStack { ProgressView(); VStack(alignment: .leading) { Text(title).bold(); Text(message).foregroundStyle(.secondary) } } }.padding() } }
struct SectionHeader: View { let title: String; let subtitle: String?; var body: some View { VStack(alignment: .leading, spacing: 3) { Text(title).font(.title3.bold()); if let subtitle { Text(subtitle).font(.subheadline).foregroundStyle(.secondary) } }.frame(maxWidth: .infinity, alignment: .leading) } }
struct MetricTile: View { let title: String; let value: String; let footnote: String?; var body: some View { BotaplataCard { Text(title).font(.caption).foregroundStyle(.secondary); Text(value).font(.title3.weight(.semibold)).monospacedDigit(); if let footnote { Text(footnote).font(.caption).foregroundStyle(.secondary) } } } }
#Preview("Components") { ScrollView { VStack { StatusBadge(status: .active, text: "Preview fixture"); ProviderBadge(provider: .kraken); FreshnessBadge(freshness: PreviewFixtures.fresh); MoneyValue(amount: .init(79.24)); PercentageValue(value: 0.0123); OfflineBanner(); EmptyStateView(title: "Vide", message: "Fixture fictive") }.padding() }.background(BotaplataColors.background) }
