import Foundation

enum PreviewFixtureMetadata { static let source = "BOTAPLATA_PREVIEW_FIXTURE"; static let isProductionData = false }
enum PreviewFixtures {
    static let now = Date(timeIntervalSinceReferenceDate: 804_000_000)
    static let fresh = DataFreshness(status: .fresh, updatedAt: now, source: .previewFixture)
    static let stale = DataFreshness(status: .stale, updatedAt: now.addingTimeInterval(-3600), source: .previewFixture)
    static let cached = DataFreshness(status: .cached, updatedAt: now.addingTimeInterval(-900), source: .localCache)
    static let feeComplete = FeeAwareSummary(executionPrice: .init(78.90), costBasisPrice: .init(79.04), buyFeeQuote: .init(0.42), buyFeeRateEffective: 0.0026, estimatedSellFeeQuote: .init(0.44), estimatedSellFeeRate: 0.0026, estimatedSellFeeSource: "Estimation backend future", breakEvenPrice: .init(79.36), minimumProfitableExitPrice: .init(79.80), minimumNetProfitRate: 0.006, estimatedSlippageRate: 0.001, unrealizedPnLGrossQuote: .init(3.40), unrealizedPnLNetEstimatedQuote: .init(2.54), realizedPnLNetQuote: nil, totalEstimatedCycleFeesQuote: .init(0.86), liquidityRole: "taker estimé")
    static let feePartial = FeeAwareSummary(executionPrice: .init(78.90), costBasisPrice: nil, buyFeeQuote: nil, buyFeeRateEffective: nil, estimatedSellFeeQuote: nil, estimatedSellFeeRate: nil, estimatedSellFeeSource: nil, breakEvenPrice: nil, minimumProfitableExitPrice: nil, minimumNetProfitRate: nil, estimatedSlippageRate: nil, unrealizedPnLGrossQuote: nil, unrealizedPnLNetEstimatedQuote: nil, realizedPnLNetQuote: nil, totalEstimatedCycleFeesQuote: nil, liquidityRole: nil)
    static let krakenDetail = SessionDetail(id: "fixture-kraken-sol", pair: "SOL/USDC", provider: .kraken, lifecycle: .positionOpen, runtimeHealth: .healthy, freshness: fresh, currentPrice: .init(79.24), position: OpenPosition(pair: "SOL/USDC", quantity: 12.5, averageExecutionPrice: .init(78.90), costBasisPrice: .init(79.04)), decision: StrategyDecisionSummary(title: "Décision actuelle", detail: "Botaplata attend une opportunité de sortie.", favorableConditions: nil, requiredConditions: nil), activeOrder: nil, pnl: ProfitAndLoss(gross: .init(3.40), netEstimated: .init(2.54), realizedNet: nil), feeAware: feeComplete, warnings: [])
    static let waitingBuy = SessionDetail(id: "fixture-waiting-buy", pair: "SOL/USDC", provider: .kraken, lifecycle: .waitingBuy, runtimeHealth: .healthy, freshness: fresh, currentPrice: .init(79.24), position: nil, decision: StrategyDecisionSummary(title: "Entrée", detail: "3 conditions sont favorables sur les 4 nécessaires. Aucun achat n'est envoyé.", favorableConditions: 3, requiredConditions: 4), activeOrder: nil, pnl: nil, feeAware: feePartial, warnings: [])
    static let waitingBuyFill = SessionDetail(id: "fixture-waiting-fill", pair: "SOL/USDC", provider: .kraken, lifecycle: .waitingBuyFill, runtimeHealth: .healthy, freshness: fresh, currentPrice: .init(79.24), position: nil, decision: StrategyDecisionSummary(title: "Ordre", detail: "L'ordre d'achat est en attente sur Kraken.", favorableConditions: nil, requiredConditions: nil), activeOrder: TradingOrderSummary(id: "order-submitted", side: "BUY", status: .submitted, message: "Ordre transmis, non confirmé exécuté."), pnl: nil, feeAware: feePartial, warnings: [])
    static let degradedDashboard = DashboardSummary(title: "Botaplata", fixtureNotice: sourceNotice, systemHealth: SystemHealth(raspberry: .healthy, exchange: ExchangeHealth(provider: .kraken, state: .healthy, message: "Kraken disponible"), monitoring: .degraded, message: "Surveillance perturbée"), activeSession: krakenDetail, warnings: [Warning(id: "degraded", severity: .warning, title: "Surveillance perturbée", message: "La surveillance rencontre actuellement un problème.")])
    static let noActiveDashboard = DashboardSummary(title: "Botaplata", fixtureNotice: sourceNotice, systemHealth: nominalHealth, activeSession: nil, warnings: [])
    static let offlineDashboard = DashboardSummary(title: "Botaplata", fixtureNotice: sourceNotice, systemHealth: nominalHealth, activeSession: krakenDetail, warnings: [Warning(id: "offline", severity: .warning, title: "Hors ligne", message: "Connexion momentanément indisponible. Dernier état connu affiché.")])
    static let nominalHealth = SystemHealth(raspberry: .healthy, exchange: ExchangeHealth(provider: .kraken, state: .healthy, message: "Kraken disponible"), monitoring: .healthy, message: "Botaplata fonctionne normalement")
    static let sourceNotice = "Données fictives — \(PreviewFixtureMetadata.source)"
    static let dashboardNominalKraken = DashboardSummary(title: "Botaplata", fixtureNotice: sourceNotice, systemHealth: nominalHealth, activeSession: krakenDetail, warnings: [])
    static let sessionSummaries = [SessionSummary(id: krakenDetail.id, pair: "SOL/USDC", provider: .kraken, lifecycle: .positionOpen, runtimeHealth: .healthy, freshness: fresh, executionMode: .spotProduction), SessionSummary(id: "fixture-binance-legacy", pair: "BTC/USDT", provider: .binanceLegacy, lifecycle: .stopped, runtimeHealth: .unknown, freshness: stale, executionMode: .legacyReadOnly)]
    static func detail(for id: String) -> SessionDetail { id == "fixture-binance-legacy" ? SessionDetail(id: id, pair: "BTC/USDT", provider: .binanceLegacy, lifecycle: .stopped, runtimeHealth: .unknown, freshness: stale, currentPrice: nil, position: nil, decision: StrategyDecisionSummary(title: "Historique Binance", detail: "Historique en lecture seule. Binance n'est pas le provider recommandé.", favorableConditions: nil, requiredConditions: nil), activeOrder: nil, pnl: nil, feeAware: feePartial, warnings: []) : krakenDetail }
    static let orders = [TradingOrderSummary(id:"submitted", side:"BUY", status:.submitted, message:"Transmis, pas exécuté"), .init(id:"partial", side:"BUY", status:.partiallyFilled, message:"Exécution partielle"), .init(id:"recon", side:"BUY", status:.reconciliationRequired, message:"Botaplata vérifie encore l'état de cet ordre sur Kraken."), .init(id:"filled", side:"BUY", status:.filled, message:"Achat confirmé par Kraken."), .init(id:"rejected", side:"BUY", status:.rejected, message:"Rejeté, aucune position ouverte.")]
    static let journalEvents = ["Décision sans achat — aucun achat n'est envoyé.", "BUY confirmé — Achat confirmé par Kraken.", "Position ouverte — surveillance de sortie.", "Sortie surveillée — attente des conditions.", "Warning technique — surveillance perturbée."]
    static let profile = ["Identité", "Sécurité", "Appareils autorisés", "Notifications", "Environnement", "Diagnostics", "À propos"]
}
