import Foundation

struct RealSessionsPageDTO: Codable, Equatable, Sendable { let items: [RealSessionSummaryDTO]; let pagination: RealSessionsPaginationDTO }
struct RealSessionsPaginationDTO: Codable, Equatable, Sendable { let page: Int; let pageSize: Int; let total: Int; let hasMore: Bool; enum CodingKeys: String, CodingKey { case page, total; case pageSize = "page_size", hasMore = "has_more" } }
struct RealSessionSummaryDTO: Codable, Equatable, Sendable {
    let id: String; let name: String?; let provider: String?; let providerLabel: String?; let executionMode: String?; let symbol: String?; let displaySymbol: String?; let status: String?; let lifecycleState: String?
    let monitoring: RealMonitoringDTO?; let freshness: RealFreshnessDTO?; let position: RealSessionSummaryPositionDTO?; let activeOrder: RealSessionSummaryOrderDTO?; let strategy: RealSessionStrategyDTO?
    let startedAt: Date?; let stoppedAt: Date?; let updatedAt: Date?; let realizedPnlNetQuote: DecimalString?; let unrealizedPnlQuote: DecimalString?
    enum CodingKeys: String, CodingKey { case id, name, provider, status, monitoring, freshness, position, strategy, symbol; case providerLabel = "provider_label", executionMode = "execution_mode", displaySymbol = "display_symbol", lifecycleState = "lifecycle_state", activeOrder = "active_order", startedAt = "started_at", stoppedAt = "stopped_at", updatedAt = "updated_at", realizedPnlNetQuote = "realized_pnl_net_quote", unrealizedPnlQuote = "unrealized_pnl_quote" }
}
struct RealSessionSummaryPositionDTO: Codable, Equatable, Sendable { let isOpen: Bool?; let status: String?; let baseQty: DecimalString?; let currentPrice: DecimalString?; enum CodingKeys: String, CodingKey { case status; case isOpen = "is_open", baseQty = "base_qty", currentPrice = "current_price" } }
struct RealSessionSummaryOrderDTO: Codable, Equatable, Sendable { let side: String?; let status: String?; let exchangeOrderID: String?; enum CodingKeys: String, CodingKey { case side, status; case exchangeOrderID = "exchange_order_id" } }
struct RealSessionStrategyDTO: Codable, Equatable, Sendable { let key: String?; let version: String?; let displayName: String?; enum CodingKeys: String, CodingKey { case key, version; case displayName = "display_name" } }
struct RealSessionDetailDTO: Codable, Equatable, Sendable {
    let id: String; let name: String?; let status: String?; let provider: String?; let providerLabel: String?; let executionMode: String?; let symbol: String?; let displaySymbol: String?; let quoteAsset: String?; let baseAsset: String?
    let strategyKey: String?; let strategyID: String?; let strategyVersion: String?; let strategyDisplayName: String?; let decisionTimeframe: String?; let riskTimeframe: String?
    let startedAt: Date?; let stoppedAt: Date?; let stopReason: String?; let createdAt: Date?; let updatedAt: Date?; let lifecycleState: String?
    let monitoring: RealMonitoringDTO?; let freshness: RealFreshnessDTO?; let market: RealMarketDTO?; let decision: RealDecisionDTO?; let position: RealPositionDTO?; let activeOrder: RealOrderDTO?; let reconciliation: RealReconciliationDTO?; let feeAware: RealFeeAwareDTO?; let pnl: RealSessionPnLDTO?
    enum CodingKeys: String, CodingKey { case id, name, status, provider, symbol, monitoring, freshness, market, decision, position, reconciliation, pnl; case providerLabel = "provider_label", executionMode = "execution_mode", displaySymbol = "display_symbol", quoteAsset = "quote_asset", baseAsset = "base_asset", strategyKey = "strategy_key", strategyID = "strategy_id", strategyVersion = "strategy_version", strategyDisplayName = "strategy_display_name", decisionTimeframe = "decision_timeframe", riskTimeframe = "risk_timeframe", startedAt = "started_at", stoppedAt = "stopped_at", stopReason = "stop_reason", createdAt = "created_at", updatedAt = "updated_at", lifecycleState = "lifecycle_state", activeOrder = "active_order", feeAware = "fee_aware" }
}
struct RealSessionPnLDTO: Codable, Equatable, Sendable { let realizedPnlQuote: DecimalString?; let realizedPnlNetQuote: DecimalString?; let unrealizedPnlQuote: DecimalString?; let unrealizedPnlNetEstimatedQuote: DecimalString?; enum CodingKeys: String, CodingKey { case realizedPnlQuote = "realized_pnl_quote", realizedPnlNetQuote = "realized_pnl_net_quote", unrealizedPnlQuote = "unrealized_pnl_quote", unrealizedPnlNetEstimatedQuote = "unrealized_pnl_net_estimated_quote" } }
