import Foundation

struct RealSessionsPage: Equatable, Sendable, Codable { let items: [SessionSummary]; let pagination: RealSessionsPagination; let warnings: [Warning]; let serverTime: Date? }
struct RealSessionsPagination: Equatable, Sendable, Codable { let page: Int; let pageSize: Int; let total: Int; let hasMore: Bool }

extension RealSessionsPageDTO { func mapped(warnings apiWarnings: [APIWarning] = [], serverTime: Date? = nil) -> RealSessionsPage { RealSessionsPage(items: items.map { $0.mapped() }, pagination: RealSessionsPagination(page: pagination.page, pageSize: pagination.pageSize, total: pagination.total, hasMore: pagination.hasMore), warnings: apiWarnings.map(Warning.init(api:)), serverTime: serverTime) } }
extension RealSessionSummaryDTO { func mapped() -> SessionSummary { let quote = resolvedQuoteAsset(displaySymbol: displaySymbol, symbol: symbol); return SessionSummary(id: id, pair: displaySymbol ?? symbol ?? name ?? id, provider: TradingProvider(backend: provider), providerLabel: providerLabel, backendStatus: status, lifecycle: SessionLifecycleState(backend: lifecycleState), runtimeHealth: RuntimeHealthState(backend: monitoring?.health), freshness: freshness.mapped(generatedAt: updatedAt), executionMode: ExecutionMode(backend: executionMode), isPositionOpen: position?.isOpen, positionStatus: position?.status, baseQuantity: position?.baseQty?.value, currentPrice: position?.currentPrice.money(quote), activeOrderSide: activeOrder?.side, activeOrderStatus: activeOrder?.status.map(OrderStatus.init(backend:)), strategyName: strategy?.displayName ?? strategy?.key, startedAt: startedAt, stoppedAt: stoppedAt, updatedAt: updatedAt, unrealizedPnLQuote: unrealizedPnlQuote.money(quote), realizedPnLNetQuote: realizedPnlNetQuote.money(quote)) } }
extension RealSessionDetailDTO { func mapped(warnings apiWarnings: [APIWarning] = []) -> SessionDetail { let pair = displaySymbol ?? symbol ?? name ?? id; let quote = resolvedQuoteAsset(displaySymbol: displaySymbol, symbol: symbol, fallback: quoteAsset ?? market?.quoteAsset); let lifecycle = SessionLifecycleState(backend: lifecycleState); let fee = feeAware?.mapped(currency: quote) ?? .empty; let gross = pnl?.unrealizedPnlQuote.money(quote) ?? fee.unrealizedPnLGrossQuote; let net = pnl?.unrealizedPnlNetEstimatedQuote.money(quote) ?? fee.unrealizedPnLNetEstimatedQuote; let realized = pnl?.realizedPnlNetQuote.money(quote) ?? fee.realizedPnLNetQuote; return SessionDetail(id: id, pair: pair, provider: TradingProvider(backend: provider), providerLabel: providerLabel, backendStatus: status, lifecycle: lifecycle, runtimeHealth: RuntimeHealthState(backend: monitoring?.health), monitoringConsecutiveErrors: monitoring?.consecutiveErrors, freshness: freshness.mapped(generatedAt: updatedAt), executionMode: ExecutionMode(backend: executionMode), startedAt: startedAt, stoppedAt: stoppedAt, strategyName: strategyDisplayName ?? strategyKey, currentPrice: market?.currentPrice.money(quote), position: position?.mapped(pair: pair, currency: quote), decision: decision?.mapped() ?? StrategyDecisionSummary(title: DashboardPresentation.wording(for: lifecycle).title, detail: DashboardPresentation.wording(for: lifecycle).text, favorableConditions: nil, requiredConditions: nil), activeOrder: activeOrder?.mapped(currency: quote), reconciliation: reconciliation?.mapped(), pnl: ProfitAndLoss(gross: gross, netEstimated: net, realizedNet: realized), feeAware: fee, warnings: apiWarnings.map(Warning.init(api:))) } }
extension RealReconciliationDTO { func mapped() -> Warning? { guard required == true || state == "reconciliation_pending" else { return nil }; return Warning(id: "reconciliation_pending", severity: .information, title: "Vérification en cours", message: "Botaplata vérifie encore l'état de cet ordre sur Kraken.") } }
extension Warning {
    init(api: APIWarning) {
        self.init(id: api.code, severity: api.code == "monitoring_degraded" || api.code == "stale_session_data" ? .warning : .information, title: Self.title(for: api.code), message: api.message)
    }
    static func title(for code: String) -> String {
        switch code { case "monitoring_degraded": return "Surveillance perturbée"; case "stale_session_data": return "Données à vérifier"; case "multiple_active_real_sessions": return "Plusieurs sessions actives"; default: return "Information Botaplata" }
    }
}
extension ExecutionMode { init(backend: String?) { switch backend { case "spot_production", "spotProduction": self = .spotProduction; case "legacy_read_only": self = .legacyReadOnly; case "demo_fixture": self = .demoFixture; default: self = .unknown } } }
private func resolvedQuoteAsset(displaySymbol: String?, symbol: String?, fallback: String? = nil) -> String {
    fallback ?? quoteAsset(from: displaySymbol ?? symbol) ?? "USDC"
}

private func quoteAsset(from pair: String?) -> String? { pair?.split(separator: "/").last.map(String.init) }
