import Foundation

extension TimelinePageDTO { func mapped(warnings: [APIWarning], serverTime: Date?) -> TimelinePage { TimelinePage(items: items.map { $0.mapped() }, pagination: RealSessionsPagination(page: pagination.page, pageSize: pagination.pageSize, total: pagination.total, hasMore: pagination.hasMore), warnings: warnings.map(Warning.init(api:)), serverTime: serverTime) } }
extension TimelineEventDTO { func mapped() -> TimelineEvent { TimelineEvent(id: id, occurredAt: occurredAt, type: TimelineEventType(rawValue: type ?? "") ?? .unknown, severity: TimelineSeverity(rawValue: severity ?? "") ?? .neutral, title: title ?? "Information Botaplata", message: message ?? "Un événement a été enregistré pour cette session.", relatedOrderID: relatedOrderID, relatedPositionID: relatedPositionID, money: money?.mapped()) } }
extension TimelineMoneyDTO { func mapped() -> TimelineMoney { TimelineMoney(amountQuote: amountQuote.money(currency ?? "USDC")) } }
extension OrdersPageDTO { func mapped(warnings: [APIWarning], serverTime: Date?) -> OrdersPage { OrdersPage(items: items.map { $0.mapped() }, pagination: RealSessionsPagination(page: pagination.page, pageSize: pagination.pageSize, total: pagination.total, hasMore: pagination.hasMore), warnings: warnings.map(Warning.init(api:)), serverTime: serverTime) } }
extension SessionOrderDTO { func mapped() -> SessionOrder { let quote = historyQuoteAsset(symbol) ?? "USDC"; return SessionOrder(id: id, side: HistoryOrderSide(rawValue: side?.lowercased() ?? "") ?? .unknown, orderType: orderType, status: OrderStatus(backend: status), statusLabel: statusLabel, provider: TradingProvider(backend: provider), exchangeOrderID: exchangeOrderID, symbol: symbol ?? "Session", requestedQuantity: requestedQuantity?.value, executedQuantity: executedQuantity?.value, limitPrice: limitPrice.money(quote), averageFillPrice: averageFillPrice.money(quote), requestedQuoteAmount: requestedQuoteAmount.money(quote), executedQuoteAmount: executedQuoteAmount.money(quote), feesQuote: feesQuote.money(quote), feeRateEffective: feeRateEffective?.value, liquidityRole: liquidityRole, reconciliationState: reconciliationState, createdAt: createdAt, updatedAt: updatedAt, filledAt: filledAt, realizedPnLQuote: realizedPnlQuote.money(quote), realizedPnLNetQuote: realizedPnlNetQuote.money(quote)) } }
extension DecisionsPageDTO { func mapped(warnings: [APIWarning], serverTime: Date?) -> DecisionsPage { DecisionsPage(items: items.map { $0.mapped() }, pagination: RealSessionsPagination(page: pagination.page, pageSize: pagination.pageSize, total: pagination.total, hasMore: pagination.hasMore), warnings: warnings.map(Warning.init(api:)), serverTime: serverTime) } }
extension SessionDecisionDTO { func mapped() -> SessionDecision { SessionDecision(id: id, createdAt: createdAt, decision: decision, decisionLabel: decisionLabel, score: score?.value, scoreMin: scoreMin?.value, price: price.money("USDC"), controller: controller, blockers: blockers ?? [], buyConditions: buyConditions ?? [], sellConditions: sellConditions ?? [], advice: advice ?? [], summaryTitle: summaryTitle ?? decisionLabel ?? "Analyse effectuée", summaryMessage: summaryMessage ?? "Botaplata a analysé les conditions de marché.") } }
extension SessionChartDTO { func mapped(warnings apiWarnings: [APIWarning], serverTime: Date?) -> SessionChart { let quote = quoteAsset ?? historyQuoteAsset(displaySymbol ?? symbol) ?? "USDC"; return SessionChart(sessionID: sessionID, symbol: symbol ?? displaySymbol ?? sessionID, displaySymbol: displaySymbol ?? symbol ?? sessionID, quoteAsset: quote, timeframe: timeframe, points: points.enumerated().compactMap { $0.element.mapped(index: $0.offset, quote: quote) }, markers: markers.map { $0.mapped(quote: quote) }, levels: levels?.mapped(quote: quote) ?? ChartLevels(executionPrice: nil, costBasisPrice: nil, breakEvenPrice: nil, minimumProfitableExitPrice: nil), warnings: apiWarnings.map(Warning.init(api:)), serverTime: serverTime) } }
extension ChartPointDTO { func mapped(index: Int, quote: String) -> ChartPoint? { guard let price else { return nil }; return ChartPoint(id: "point-\(index)-\(Int(timestamp.timeIntervalSince1970))", timestamp: timestamp, price: MoneyAmount(price.value, currency: quote)) } }
extension ChartMarkerDTO { func mapped(quote: String) -> ChartMarker { ChartMarker(id: id, timestamp: timestamp, type: ChartMarkerType(rawValue: type?.lowercased() ?? "") ?? .unknown, label: label ?? ChartMarkerType(rawValue: type?.lowercased() ?? "")?.label ?? "Transaction confirmée", price: price.money(quote), quantity: quantity?.value, quoteAmount: quoteAmount.money(quote)) } }
extension ChartLevelsDTO { func mapped(quote: String) -> ChartLevels { ChartLevels(executionPrice: executionPrice.money(quote), costBasisPrice: costBasisPrice.money(quote), breakEvenPrice: breakEvenPrice.money(quote), minimumProfitableExitPrice: minimumProfitableExitPrice.money(quote)) } }
extension Optional where Wrapped == DecimalString { func money(_ currency: String) -> MoneyAmount? { guard let self else { return nil }; return MoneyAmount(self.value, currency: currency) } }
private func historyQuoteAsset(_ pair: String?) -> String? { pair?.split(separator: "/").last.map(String.init) }
