import Foundation

struct RealStrategyExplanationDTO: Decodable, Sendable { let data: RealStrategyExplanationDataDTO; let meta: StrategyExplanationMetaDTO }
struct RealStrategyExplanationDataDTO: Decodable, Sendable { let sessionID: String; let strategy: StrategyIdentityDTO; let decision: StrategyExplanationDecisionDTO; let score: StrategyExplanationScoreDTO?; let analysis: StrategyExplanationAnalysisDTO; let market: StrategyExplanationMarketDTO; let conditions: [StrategyExplanationConditionDTO]; let blockers: [StrategyExplanationBlockerDTO]; let indicators: StrategyExplanationIndicatorsDTO; let positionProtection: StrategyExplanationPositionProtectionDTO?; let warnings: [StrategyExplanationWarningDTO]; enum CodingKeys: String, CodingKey { case strategy, decision, score, analysis, market, conditions, blockers, indicators, warnings; case sessionID = "session_id", positionProtection = "position_protection" } }
struct StrategyIdentityDTO: Decodable, Sendable { let code: String; let name: String; let version: String? }
struct StrategyExplanationDecisionDTO: Decodable, Sendable { let code: String; let label: String; let summary: String; let technicalDetail: String?; let status: String?; let decidedAt: Date?; enum CodingKeys: String, CodingKey { case code, label, summary, status; case technicalDetail = "technical_detail", decidedAt = "decided_at" } }
struct StrategyExplanationScoreDTO: Decodable, Sendable { let current: String?; let required: String?; let maximum: String?; let favorableConditions: Int?; let totalConditions: Int?; let summary: String?; enum CodingKeys: String, CodingKey { case current, required, maximum, summary; case favorableConditions = "favorable_conditions", totalConditions = "total_conditions" } }
struct StrategyExplanationAnalysisDTO: Decodable, Sendable { let timeframe: String?; let candleCloseTime: Date?; let calculatedAt: Date?; let nextRecalculationAt: Date?; let freshness: StrategyExplanationFreshnessDTO?; let summary: String?; let technicalDetail: String?; enum CodingKeys: String, CodingKey { case timeframe, freshness, summary; case candleCloseTime = "candle_close_time", calculatedAt = "calculated_at", nextRecalculationAt = "next_recalculation_at", technicalDetail = "technical_detail" } }
struct StrategyExplanationFreshnessDTO: Decodable, Sendable { let status: String?; let label: String?; let summary: String?; let isStale: Bool?; enum CodingKeys: String, CodingKey { case status, label, summary; case isStale = "is_stale" } }
struct StrategyExplanationMarketDTO: Decodable, Sendable { let regime: StrategyExplanationRegimeDTO; let momentum: StrategyExplanationMomentumDTO; let summary: String? }
struct StrategyExplanationRegimeDTO: Decodable, Sendable { let code: String; let label: String; let summary: String? }
struct StrategyExplanationMomentumDTO: Decodable, Sendable { let code: String; let label: String; let summary: String? }
struct StrategyExplanationConditionDTO: Decodable, Sendable { let id: String; let code: String?; let label: String; let status: String; let summary: String; let value: String?; let threshold: String?; let technicalDetail: String?; enum CodingKeys: String, CodingKey { case id, code, label, status, summary, value, threshold; case technicalDetail = "technical_detail" } }
struct StrategyExplanationBlockerDTO: Decodable, Sendable { let id: String; let code: String?; let label: String; let summary: String; let severity: String; let recoverable: Bool?; let technicalDetail: String?; enum CodingKeys: String, CodingKey { case id, code, label, summary, severity, recoverable; case technicalDetail = "technical_detail" } }
struct StrategyExplanationIndicatorsDTO: Decodable, Sendable { let rsi: StrategyExplanationIndicatorDTO?; let adx: StrategyExplanationIndicatorDTO?; let atr: StrategyExplanationIndicatorDTO?; let vwap: StrategyExplanationIndicatorDTO?; let ema200: StrategyExplanationIndicatorDTO?; let ema200Slope: StrategyExplanationIndicatorDTO?; let bollinger: StrategyExplanationIndicatorDTO?; enum CodingKeys: String, CodingKey { case rsi, adx, atr, vwap, bollinger; case ema200 = "ema200", ema200Slope = "ema200_slope" } }
struct StrategyExplanationIndicatorDTO: Decodable, Sendable { let value: String?; let label: String?; let status: String?; let summary: String?; let technicalDetail: String?; enum CodingKeys: String, CodingKey { case value, label, status, summary; case technicalDetail = "technical_detail" } }
struct StrategyExplanationPositionProtectionDTO: Decodable, Sendable { let summary: String; let entryPrice: String?; let currentPrice: String?; let unrealizedPnL: String?; let breakEvenPrice: String?; let minimumProfitablePrice: String?; let trailingActive: Bool?; let trailingStop: String?; let sellConditions: [String]; let technicalDetail: String?; enum CodingKeys: String, CodingKey { case summary; case entryPrice = "entry_price", currentPrice = "current_price", unrealizedPnL = "unrealized_pnl", breakEvenPrice = "break_even_price", minimumProfitablePrice = "minimum_profitable_price", trailingActive = "trailing_active", trailingStop = "trailing_stop", sellConditions = "sell_conditions", technicalDetail = "technical_detail" } }
struct StrategyExplanationWarningDTO: Decodable, Sendable { let id: String; let severity: String; let title: String; let message: String }
struct StrategyExplanationMetaDTO: Decodable, Sendable { let requestID: String?; let serverTime: Date?; let generatedAt: Date?; let dataSource: String?; enum CodingKeys: String, CodingKey { case requestID = "request_id", serverTime = "server_time", generatedAt = "generated_at", dataSource = "data_source" } }
