import Foundation
import OSLog

extension RealStrategyExplanationDTO { func mapped() -> StrategyExplanation { data.mapped(metaDTO: meta) } }
extension RealStrategyExplanationDataDTO {
    func mapped(metaDTO: StrategyExplanationMetaDTO) -> StrategyExplanation {
        let mapped = StrategyExplanation(sessionID: sessionID, strategy: .init(id: strategy.id, code: strategy.code ?? strategy.id, label: strategy.label ?? strategy.code ?? strategy.id, version: strategy.version), decision: .init(rawValue: decision.code, code: .init(backend: decision.code), label: decision.label, summary: decision.summary, technicalDetail: decision.technicalDetail, status: decision.status, decidedAt: decision.decidedAt), score: score.map { .init(currentRaw: $0.current, current: Self.decimal($0.current), requiredRaw: $0.required, required: Self.decimal($0.required), maximumRaw: $0.maximum, maximum: Self.decimal($0.maximum), favorableConditions: $0.favorableConditions, totalConditions: $0.totalConditions, summary: $0.summary) }, analysis: .init(timeframe: analysis.timeframe, candleCloseTime: analysis.candleCloseTime, calculatedAt: analysis.calculatedAt, nextRecalculationAt: analysis.nextRecalculationAt, freshness: .init(status: analysis.freshness?.status ?? "unknown", label: analysis.freshness?.label, summary: analysis.freshness?.summary, isStale: analysis.freshness?.isStale ?? analysis.freshness?.status == "stale"), summary: analysis.summary, technicalDetail: analysis.technicalDetail), market: .init(regime: .init(rawValue: market.regime.code, code: .init(backend: market.regime.code), label: market.regime.label, summary: market.regime.summary), momentum: .init(rawValue: market.momentum.code, code: .init(backend: market.momentum.code), label: market.momentum.label, summary: market.momentum.summary), summary: market.summary), conditions: conditions.map { .init(id: $0.id, code: $0.code ?? $0.id, label: $0.label, status: .init(backend: $0.status), statusRaw: $0.status, summary: $0.summary, valueRaw: $0.value, thresholdRaw: $0.threshold, technicalDetail: $0.technicalDetail) }, blockers: blockers.map { .init(id: $0.id, code: $0.code ?? $0.id, label: $0.label, summary: $0.summary, severity: .init(backend: $0.severity), severityRaw: $0.severity, recoverable: $0.recoverable, technicalDetail: $0.technicalDetail) }, indicators: indicators.mapped(), positionProtection: positionProtection.map { .init(summary: $0.summary, entryPriceRaw: $0.entryPrice, currentPriceRaw: $0.currentPrice, unrealizedPnLRaw: $0.unrealizedPnL, breakEvenPriceRaw: $0.breakEvenPrice, minimumProfitablePriceRaw: $0.minimumProfitablePrice, trailingActive: $0.trailingActive, trailingStopRaw: $0.trailingStop, sellConditions: $0.sellConditions, technicalDetail: $0.technicalDetail) }, warnings: warnings.map { .init(id: $0.id, severity: .init(backend: $0.severity), title: $0.title, message: $0.message) }, meta: .init(requestID: metaDTO.requestID, serverTime: metaDTO.serverTime, generatedAt: metaDTO.generatedAt, source: metaDTO.source))
        BotaplataLog.strategyExplanation.info("StrategyExplanationMapper decision=\(mapped.decision.rawValue, privacy: .public) score=\(mapped.score?.currentRaw ?? "nil", privacy: .public)/\(mapped.score?.requiredRaw ?? "nil", privacy: .public) conditions=\(mapped.conditions.count, privacy: .public) blockers=\(mapped.blockers.count, privacy: .public)")
        return mapped
    }
    private static func decimal(_ raw: String?) -> Decimal? { raw.flatMap { Decimal(string: $0, locale: Locale(identifier: "en_US_POSIX")) } }
}
extension StrategyExplanationIndicatorsDTO { func mapped() -> StrategyIndicatorSet { StrategyIndicatorSet(indicators: [("rsi", "RSI", rsi, "Le RSI mesure si le marché a beaucoup monté ou baissé récemment."), ("adx", "ADX", adx, "L’ADX indique si le marché suit une tendance forte ou évolue plus librement."), ("atr", "ATR", atr, "L’ATR mesure l’amplitude habituelle des mouvements de prix."), ("vwap", "VWAP", vwap, "Le VWAP représente le prix moyen pondéré par les volumes."), ("ema200", "EMA200", ema200, "L’EMA200 donne une vision de la tendance de fond."), ("ema200_slope", "Pente EMA200", ema200Slope, "La pente EMA200 décrit la tendance de fond fournie par le serveur."), ("bollinger", "Bollinger", bollinger, "Les bandes de Bollinger aident à situer le prix dans sa zone récente d’évolution.")].compactMap { id, name, dto, help in guard let dto else { return nil }; return StrategyIndicator(id: id, name: dto.label ?? name, valueRaw: dto.value, status: dto.status, help: dto.summary ?? help, technicalDetail: dto.technicalDetail) }) } }
