import SwiftUI
#if canImport(Charts)
import Charts
#endif

struct JournalContainerView: View { @State var historyStore: RealSessionHistoryStore; @State var sessionsStore: RealSessionsStore; @State private var selectedSessionID: String?
    var sessions: [SessionSummary] { sessionsStore.visibleItems }
    var selected: SessionSummary? { sessions.first { $0.id == selectedSessionID } ?? sessions.first { !$0.isHistorical } ?? sessions.first }
    var body: some View { JournalView(session: selected, sessions: sessions, content: selected.map { historyStore.timelines[$0.id] ?? .idle } ?? .loaded([]), warnings: selected.map { historyStore.warnings[$0.id] ?? [] } ?? [], select: { selectedSessionID = $0 }, loadNext: { if let id = selected?.id { await historyStore.loadNextTimeline(sessionID: id) } }, refresh: { await sessionsStore.refresh(); if let id = selected?.id { await historyStore.refreshTimeline(sessionID: id) } }).task { await historyStore.loadCache(); sessionsStore.start(); if let id = selected?.id { selectedSessionID = id; await historyStore.refreshTimeline(sessionID: id) } }.onChange(of: selected?.id) { _, id in if let id { selectedSessionID = id; Task { await historyStore.refreshTimeline(sessionID: id) } } } }
}

struct JournalView: View { let session: SessionSummary?; let sessions: [SessionSummary]; let content: LoadedContent<[TimelineEvent]>; var warnings: [Warning] = []; var select: (String) -> Void = { _ in }; var loadNext: () async -> Void = {}; var refresh: () async -> Void = {}
    var body: some View { List { header; if isOffline { Text("Connexion momentanément indisponible. Dernier état connu affiché.").font(.caption).foregroundStyle(BotaplataColors.warning) }; ForEach(warnings) { Text(HistoryPresentation.warning($0)).font(.caption).foregroundStyle(BotaplataColors.warning) }; bodyContent }.navigationTitle("Journal").scrollContentBackground(.hidden).background(BotaplataColors.background).refreshable { await refresh() } }
    @ViewBuilder var header: some View { if sessions.isEmpty { EmptyView() } else { Menu { ForEach(sessions) { s in Button("\(s.pair) · \(DashboardPresentation.wording(for: s.lifecycle).title)") { select(s.id) } } } label: { HStack { Text(session.map { "\($0.pair) · \($0.provider.displayName)" } ?? "Choisir une session").font(.headline); Spacer(); Image(systemName: "chevron.down") } }.listRowBackground(Color.clear) } }
    @ViewBuilder var bodyContent: some View { switch content { case .idle, .loading: BotaplataCard { Text("Chargement du Journal…").font(.headline); Text("Botaplata récupère l'activité réelle.").foregroundStyle(.secondary) }; case .error: EmptyStateView(title: "Impossible de charger le Journal", message: "Vérifiez votre connexion puis réessayez."); case .loaded(let e), .loadedFromCache(let e), .refreshing(let e?), .offline(let e?), .partial(let e), .stale(let e): if session == nil { EmptyStateView(title: "Aucune session à afficher", message: "Le Journal affichera l'activité de Botaplata lorsqu'une session Kraken réelle sera disponible.") } else if e.isEmpty { EmptyStateView(title: "Aucune activité enregistrée", message: "Aucun événement n'est encore disponible pour cette session.") } else { ForEach(HistoryPresentation.group(e), id: \.title) { group in Section(group.title) { ForEach(group.items) { event in TimelineRow(event: event).task { if event.id == e.last?.id { await loadNext() } } } } } }; case .refreshing(nil), .offline(nil): EmptyStateView(title: "Impossible de charger le Journal", message: "Vérifiez votre connexion puis réessayez.") } }
    var isOffline: Bool { if case .offline = content { true } else { false } }
}

struct TimelineRow: View { let event: TimelineEvent; var body: some View { HStack(alignment: .top, spacing: 12) { Text(HistoryPresentation.time(event.occurredAt)).font(.caption.monospacedDigit()).foregroundStyle(.secondary).frame(width: 48, alignment: .leading); Image(systemName: HistoryPresentation.icon(event)).foregroundStyle(HistoryPresentation.color(event.severity)); VStack(alignment: .leading, spacing: 4) { Text(event.title).font(.headline); Text(event.message).foregroundStyle(.secondary) } }.padding(.vertical, 6).accessibilityElement(children: .combine).accessibilityLabel("\(event.title), \(HistoryPresentation.fullDate(event.occurredAt)), \(event.message)") } }

struct OrdersHistoryView: View { let session: SessionDetail; @State var store: RealSessionHistoryStore; var body: some View { PagedHistoryList(title: "Ordres", content: store.orders[session.id] ?? .idle, emptyTitle: "Aucun ordre", emptyMessage: "Aucun ordre n'est disponible pour cette session.", loadNext: { await store.loadNextOrders(sessionID: session.id) }, row: { OrderRow(order: $0) }).task { await store.refreshOrders(sessionID: session.id) }.refreshable { await store.refreshOrders(sessionID: session.id) } } }
struct DecisionsHistoryView: View { let session: SessionDetail; @State var store: RealSessionHistoryStore; var body: some View { PagedHistoryList(title: "Décisions", content: store.decisions[session.id] ?? .idle, emptyTitle: "Aucune décision", emptyMessage: "Aucune décision n'est disponible pour cette session.", loadNext: { await store.loadNextDecisions(sessionID: session.id) }, row: { DecisionRow(decision: $0) }).task { await store.refreshDecisions(sessionID: session.id) }.refreshable { await store.refreshDecisions(sessionID: session.id) } } }
struct SessionJournalHistoryView: View { let session: SessionDetail; @State var store: RealSessionHistoryStore; var body: some View { JournalView(session: SessionSummary(id: session.id, pair: session.pair, provider: session.provider, providerLabel: session.providerLabel, backendStatus: session.backendStatus, lifecycle: session.lifecycle, runtimeHealth: session.runtimeHealth, freshness: session.freshness, executionMode: session.executionMode), sessions: [], content: store.timelines[session.id] ?? .idle, warnings: store.warnings[session.id] ?? [], loadNext: { await store.loadNextTimeline(sessionID: session.id) }, refresh: { await store.refreshTimeline(sessionID: session.id) }).task { await store.refreshTimeline(sessionID: session.id) } } }

struct PagedHistoryList<Item: Identifiable & Sendable, Row: View>: View { let title: String; let content: LoadedContent<[Item]>; let emptyTitle: String; let emptyMessage: String; let loadNext: () async -> Void; let row: (Item) -> Row; var body: some View { List { switch content { case .idle, .loading: BotaplataCard { Text("Chargement…") }; case .error: EmptyStateView(title: "Chargement impossible", message: "Vérifiez votre connexion puis réessayez."); case .loaded(let items), .loadedFromCache(let items), .refreshing(let items?), .offline(let items?), .partial(let items), .stale(let items): if items.isEmpty { EmptyStateView(title: emptyTitle, message: emptyMessage) } else { ForEach(items) { item in row(item).task { if item.id == items.last?.id { await loadNext() } } } }; case .refreshing(nil), .offline(nil): EmptyStateView(title: "Chargement impossible", message: "Vérifiez votre connexion puis réessayez.") } }.navigationTitle(title).scrollContentBackground(.hidden).background(BotaplataColors.background) } }
struct OrderRow: View { let order: SessionOrder; var body: some View { BotaplataCard { VStack(alignment: .leading, spacing: 8) { HStack { Text(order.side.label).font(.headline); Spacer(); StatusBadge(status: order.status == .filled ? .success : order.status == .rejected ? .danger : .waiting, text: order.statusLabel ?? order.status.label) }; Text(order.orderType?.uppercased() ?? "Type indisponible").font(.caption).foregroundStyle(.secondary); row("Quantité demandée", order.requestedQuantity.map { FinancialFormatters.decimal($0, min: 2, max: 8) } ?? "Indisponible"); row("Quantité exécutée", order.executedQuantity.map { FinancialFormatters.decimal($0, min: 2, max: 8) } ?? "Indisponible"); row("Prix limite", FinancialFormatters.money(order.limitPrice)); row("Prix moyen exécuté", FinancialFormatters.money(order.averageFillPrice)); row("Montant exécuté", FinancialFormatters.money(order.executedQuoteAmount)); row("Frais", FinancialFormatters.money(order.feesQuote)); row("PnL net réalisé", FinancialFormatters.money(order.realizedPnLNetQuote) == "—" ? "Indisponible" : FinancialFormatters.money(order.realizedPnLNetQuote)); Text(HistoryPresentation.fullDate(order.filledAt ?? order.updatedAt ?? order.createdAt ?? Date())).font(.caption).foregroundStyle(.secondary) } } } ; func row(_ k: String, _ v: String) -> some View { HStack { Text(k); Spacer(); Text(v == "—" ? "Indisponible" : v).monospacedDigit() } } }
struct DecisionRow: View { let decision: SessionDecision; var body: some View { BotaplataCard { VStack(alignment: .leading, spacing: 8) { Text(HistoryPresentation.fullDate(decision.createdAt)).font(.caption).foregroundStyle(.secondary); Text(decision.summaryTitle).font(.headline); Text(decision.summaryMessage).foregroundStyle(.secondary); if let price = decision.price { Text("Prix : \(FinancialFormatters.money(price))").monospacedDigit() }; DisclosureGroup("Voir le détail de l'analyse") { DetailList(title: "Conditions favorables", items: decision.buyConditions); DetailList(title: "Points à vérifier", items: decision.sellConditions + decision.advice); DetailList(title: "Éléments bloquants", items: decision.blockers); if let s = decision.score { Text("Score technique : \(FinancialFormatters.decimal(s, min: 0, max: 4))").font(.caption).foregroundStyle(.secondary) } } } } } }
struct DetailList: View { let title: String; let items: [String]; var body: some View { if !items.isEmpty { Text(title).font(.subheadline.weight(.semibold)); ForEach(items, id: \.self) { Text("• \($0)").font(.caption).foregroundStyle(.secondary) } } } }

struct SessionChartView: View { let session: SessionDetail; @State var store: RealSessionHistoryStore; var body: some View { List { switch store.charts[session.id] ?? .idle { case .idle, .loading: BotaplataCard { Text("Chargement du graphique…") }; case .loaded(let c), .loadedFromCache(let c), .refreshing(let c?), .offline(let c?), .stale(let c): ChartContent(chart: c); case .error: EmptyStateView(title: "Graphique indisponible", message: "Vérifiez votre connexion puis réessayez."); default: EmptyStateView(title: "Graphique indisponible", message: "Vérifiez votre connexion puis réessayez.") } }.navigationTitle("Graphique").scrollContentBackground(.hidden).background(BotaplataColors.background).task { await store.refreshChart(sessionID: session.id) }.refreshable { await store.refreshChart(sessionID: session.id) } } }
struct ChartContent: View { let chart: SessionChart; var body: some View { Section(chart.displaySymbol) { if chart.points.isEmpty { BotaplataCard { Text("Courbe de prix indisponible").font(.headline); Text("Botaplata ne dispose pas encore d'une série de prix persistée pour cette session.").foregroundStyle(.secondary) } } else { chartView } }; Section("Niveaux financiers") { level("Prix moyen exécuté", chart.levels.executionPrice); level("Prix de revient frais inclus", chart.levels.costBasisPrice); level("Seuil de rentabilité", chart.levels.breakEvenPrice); level("Prix minimum rentable", chart.levels.minimumProfitableExitPrice) }; Section("Transactions confirmées") { ForEach(chart.markers) { m in VStack(alignment: .leading) { Text(m.label.isEmpty ? m.type.label : m.label).font(.headline); Text(HistoryPresentation.fullDate(m.timestamp)).font(.caption).foregroundStyle(.secondary); Text(FinancialFormatters.money(m.price)).monospacedDigit(); if let q = m.quantity { Text("\(FinancialFormatters.decimal(q, min: 2, max: 8)) \(chart.displaySymbol.split(separator: "/").first.map(String.init) ?? "")") } } } } }
    @ViewBuilder var chartView: some View {
        #if canImport(Charts)
        Chart(chart.points) {
            LineMark(x: .value("Date", $0.timestamp), y: .value("Prix", NSDecimalNumber(decimal: $0.price.value ?? 0).doubleValue))
        }
        .frame(height: 220)
        #else
        Text("Courbe disponible sur iOS avec Swift Charts.")
        #endif
    }
    func level(_ title: String, _ amount: MoneyAmount?) -> some View { HStack { Text(title); Spacer(); Text(FinancialFormatters.money(amount) == "—" ? "Indisponible" : FinancialFormatters.money(amount)).monospacedDigit() } }
}

enum HistoryPresentation { static func icon(_ e: TimelineEvent) -> String { switch e.type { case .buyFilled, .sellFilled, .positionOpened, .positionClosed: "checkmark.seal.fill"; case .monitoringDegraded, .reconciliationPending: "exclamationmark.triangle.fill"; case .error: "xmark.octagon.fill"; default: "circle.fill" } }; static func color(_ s: TimelineSeverity) -> Color { switch s { case .success: BotaplataColors.success; case .warning: BotaplataColors.warning; case .danger: BotaplataColors.danger; default: BotaplataColors.accent } }; static func time(_ d: Date) -> String { let f = DateFormatter(); f.dateFormat = "HH:mm"; return f.string(from: d) }; static func fullDate(_ d: Date) -> String { let f = DateFormatter(); f.dateStyle = .medium; f.timeStyle = .short; f.locale = Locale(identifier: "fr_FR"); return f.string(from: d) }; static func group(_ events: [TimelineEvent]) -> [(title: String, items: [TimelineEvent])] { Dictionary(grouping: events) { Calendar.current.isDateInToday($0.occurredAt) ? "Aujourd'hui" : (Calendar.current.isDateInYesterday($0.occurredAt) ? "Hier" : fullDate($0.occurredAt).components(separatedBy: " à ").first ?? fullDate($0.occurredAt)) }.map { ($0.key, $0.value.sorted { $0.occurredAt > $1.occurredAt }) }.sorted { $0.items.first?.occurredAt ?? .distantPast > $1.items.first?.occurredAt ?? .distantPast } }; static func warning(_ w: Warning) -> String { w.id == "chart_price_series_unavailable" ? "La courbe de prix n'est pas disponible pour cette session." : w.message } }

#Preview { NavigationStack { JournalView(session: PreviewFixtures.sessionSummaries.first, sessions: PreviewFixtures.sessionSummaries, content: .loaded(PreviewFixtures.timelineEvents)) } }
#Preview("Graphique sans points") { NavigationStack { ChartContent(chart: PreviewFixtures.sessionChart) } }
#Preview("Ordres") { NavigationStack { PagedHistoryList(title: "Ordres", content: .loaded(PreviewFixtures.sessionOrders), emptyTitle: "Aucun ordre", emptyMessage: "", loadNext: {}, row: { OrderRow(order: $0) }) } }
