import Foundation

struct RealSessionChartDTO: Decodable, Sendable { let sessionID: String; let symbol: String; let displaySymbol: String; let quoteAsset: String; let range: String; let timeframe: String; let generatedAt: Date; let dataSource: String; let isComplete: Bool; let hasMore: Bool; let nextBefore: Date?; let series: [RealChartCandleDTO]; let markers: [RealChartMarkerDTO]; let levels: RealChartLevelsDTO?; enum CodingKeys: String, CodingKey { case symbol, range, timeframe, series, markers, levels; case sessionID = "session_id", displaySymbol = "display_symbol", quoteAsset = "quote_asset", generatedAt = "generated_at", dataSource = "data_source", isComplete = "is_complete", hasMore = "has_more", nextBefore = "next_before" } }
struct RealChartCandleDTO: Decodable, Sendable { let id: String; let openTime: Date; let closeTime: Date; let isClosed: Bool; let open: DecimalString; let high: DecimalString; let low: DecimalString; let close: DecimalString; let volume: DecimalString?; let vwap: DecimalString?; let ema200: DecimalString?; let bollingerUpper: DecimalString?; let bollingerMiddle: DecimalString?; let bollingerLower: DecimalString?; enum CodingKeys: String, CodingKey { case id, open, high, low, close, volume, vwap, ema200; case openTime = "open_time", closeTime = "close_time", isClosed = "is_closed", bollingerUpper = "bollinger_upper", bollingerMiddle = "bollinger_middle", bollingerLower = "bollinger_lower" } }
struct RealChartMarkerDTO: Decodable, Sendable { let id: String; let kind: String; let timestamp: Date; let price: DecimalString; let quantity: DecimalString?; let orderID: String?; let label: String?; enum CodingKeys: String, CodingKey { case id, kind, timestamp, price, quantity, label; case orderID = "order_id" } }
struct RealChartLevelsDTO: Decodable, Sendable { let entryPrice: DecimalString?; let breakEvenPrice: DecimalString?; let minimumProfitableExitPrice: DecimalString?; let trailingStopPrice: DecimalString?; enum CodingKeys: String, CodingKey { case entryPrice = "entry_price", breakEvenPrice = "break_even_price", minimumProfitableExitPrice = "minimum_profitable_exit_price", trailingStopPrice = "trailing_stop_price" } }

enum TradingChartRange: String, CaseIterable, Sendable, Codable { case oneHour = "1h", sixHours = "6h", oneDay = "24h", sevenDays = "7d"; var displayTitle: String { switch self { case .oneHour: "1 h"; case .sixHours: "6 h"; case .oneDay: "24 h"; case .sevenDays: "7 j" } }; var cacheTTL: TimeInterval { switch self { case .oneHour: 30; case .sixHours: 60; case .oneDay: 120; case .sevenDays: 300 } } }
enum TradingMarkerKind: String, Sendable, Codable { case buy, sell, partialBuy, partialSell; var title: String { switch self { case .buy: "Achat confirmé"; case .sell: "Vente confirmée"; case .partialBuy: "Achat partiellement exécuté"; case .partialSell: "Vente partiellement exécutée" } } }
struct TradingCandle: Sendable, Identifiable, Equatable, Codable { let id: String; let openTime: Date; let closeTime: Date; let isClosed: Bool; let open: Decimal; let high: Decimal; let low: Decimal; let close: Decimal; let volume: Decimal?; let vwap: Decimal?; let ema200: Decimal?; let bollingerUpper: Decimal?; let bollingerMiddle: Decimal?; let bollingerLower: Decimal? }
struct TradingMarker: Sendable, Identifiable, Equatable, Codable { let id: String; let kind: TradingMarkerKind; let timestamp: Date; let price: Decimal; let quantity: Decimal?; let orderID: String?; let label: String; var title: String { label.isEmpty ? kind.title : label } }
struct TradingLevels: Sendable, Equatable, Codable { let entryPrice: Decimal?; let breakEvenPrice: Decimal?; let minimumProfitableExitPrice: Decimal?; let trailingStopPrice: Decimal? }
struct TradingChart: Sendable, Equatable, Codable { let sessionID: String; let symbol: String; let displaySymbol: String; let quoteAsset: String; let range: TradingChartRange; let timeframe: String; let generatedAt: Date; let dataSource: String; let isComplete: Bool; let hasMore: Bool; let nextBefore: Date?; let candles: [TradingCandle]; let markers: [TradingMarker]; let levels: TradingLevels; let warnings: [Warning] }

enum TradingCandleValidator { static func isValid(_ c: RealChartCandleDTO) -> Bool { c.openTime < c.closeTime && c.low.value <= c.open.value && c.open.value <= c.high.value && c.low.value <= c.close.value && c.close.value <= c.high.value && (c.volume?.value ?? 0) >= 0 } }
enum TradingChartContractError: Error, Equatable { case missingData; case unknownRange(String); case unknownMarkerKind(String) }
enum RealSessionChartMapper { static func map(envelope: APIEnvelope<RealSessionChartDTO>) throws -> TradingChart { guard let dto = envelope.data else { throw TradingChartContractError.missingData }; guard let range = TradingChartRange(rawValue: dto.range) else { throw TradingChartContractError.unknownRange(dto.range) }; var seen = Set<String>(); var candles: [TradingCandle] = []; for c in dto.series.sorted(by: { $0.openTime < $1.openTime }) { guard TradingCandleValidator.isValid(c), !seen.contains(c.id) else { continue }; seen.insert(c.id); candles.append(TradingCandle(id: c.id, openTime: c.openTime, closeTime: c.closeTime, isClosed: c.isClosed, open: c.open.value, high: c.high.value, low: c.low.value, close: c.close.value, volume: c.volume?.value, vwap: c.vwap?.value, ema200: c.ema200?.value, bollingerUpper: c.bollingerUpper?.value, bollingerMiddle: c.bollingerMiddle?.value, bollingerLower: c.bollingerLower?.value)) }
    let markers = try dto.markers.sorted(by: { $0.timestamp < $1.timestamp }).map { m -> TradingMarker in let kind: TradingMarkerKind = switch m.kind { case "buy": .buy; case "sell": .sell; case "partial_buy": .partialBuy; case "partial_sell": .partialSell; default: throw TradingChartContractError.unknownMarkerKind(m.kind) }; return TradingMarker(id: m.id, kind: kind, timestamp: m.timestamp, price: m.price.value, quantity: m.quantity?.value, orderID: m.orderID, label: m.label ?? kind.title) }
    return TradingChart(sessionID: dto.sessionID, symbol: dto.symbol, displaySymbol: dto.displaySymbol, quoteAsset: dto.quoteAsset, range: range, timeframe: dto.timeframe, generatedAt: dto.generatedAt, dataSource: dto.dataSource, isComplete: dto.isComplete, hasMore: dto.hasMore, nextBefore: dto.nextBefore, candles: candles, markers: markers, levels: TradingLevels(entryPrice: dto.levels?.entryPrice?.value, breakEvenPrice: dto.levels?.breakEvenPrice?.value, minimumProfitableExitPrice: dto.levels?.minimumProfitableExitPrice?.value, trailingStopPrice: dto.levels?.trailingStopPrice?.value), warnings: envelope.warnings.map(Warning.init(api:))) } }
