import Foundation

struct MoneyAmount: Equatable, Sendable, Codable { let value: Decimal?; let currency: String; init(_ value: Decimal?, currency: String = "USDC") { self.value = value; self.currency = currency } }
enum TradingProvider: String, CaseIterable, Sendable, Codable { case kraken, binanceLegacy, unknown; var displayName: String { switch self { case .kraken: "Kraken"; case .binanceLegacy: "Historique Binance"; case .unknown: "Provider inconnu" } } }
enum ExecutionMode: String, Sendable, Codable { case real, spotProduction, legacyReadOnly, demoFixture, unknown }
enum SessionLifecycleState: String, CaseIterable, Sendable, Codable { case waitingBuy, preparingBuy, waitingBuyFill, positionOpen, waitingSell, waitingSellFill, monitoringPosition, reconciliationPending, stopped, unknown
    var userMessage: String { switch self { case .waitingBuy: "Botaplata cherche une opportunité d'achat."; case .preparingBuy: "Botaplata prépare une intention d'achat. Aucun achat n'est envoyé depuis l'app."; case .waitingBuyFill: "L'ordre d'achat est en attente sur Kraken."; case .positionOpen, .waitingSell, .monitoringPosition: "Position ouverte. Botaplata surveille maintenant les conditions de sortie."; case .waitingSellFill: "L'ordre de vente est en attente de confirmation sur Kraken."; case .reconciliationPending: "Botaplata vérifie encore l'état de cet ordre sur Kraken."; case .stopped: "Session arrêtée."; case .unknown: "État de session inconnu." } }
    var label: String { switch self { case .waitingBuy: "Recherche BUY"; case .preparingBuy: "Préparation BUY"; case .waitingBuyFill: "BUY en attente"; case .positionOpen: "Position ouverte"; case .waitingSell: "Attente SELL"; case .waitingSellFill: "SELL en attente"; case .monitoringPosition: "Surveillance position"; case .reconciliationPending: "Vérification en cours"; case .stopped: "Arrêtée"; case .unknown: "Inconnu" } }
}
enum RuntimeHealthState: String, Sendable, Codable { case healthy, degraded, unavailable, unknown; var label: String { switch self { case .healthy: "Surveillance normale"; case .degraded: "Surveillance perturbée"; case .unavailable: "Surveillance indisponible"; case .unknown: "Santé inconnue" } } }
enum OrderStatus: String, CaseIterable, Sendable, Codable { case submissionStarted, submitted, open, partiallyFilled, filled, reconciliationRequired, reconciliationBlocked, reconciliationFailed, canceled, rejected, unknown
    var label: String { switch self { case .submissionStarted: "Préparation de l’ordre"; case .submitted: "Envoyé à Kraken"; case .open: "En attente sur Kraken"; case .partiallyFilled: "Partiellement exécuté"; case .filled: "Confirmé par Kraken"; case .reconciliationRequired: "Vérification nécessaire"; case .reconciliationBlocked: "Vérification bloquée"; case .reconciliationFailed: "Vérification échouée"; case .canceled: "Annulé"; case .rejected: "Refusé par Kraken"; case .unknown: "Inconnu" } }
}
struct TradingOrderSummary: Identifiable, Equatable, Sendable, Codable { let id: String; let side: String; let status: OrderStatus; let message: String; var requestedQuantity: Decimal? = nil; var executedQuantity: Decimal? = nil; var limitPrice: MoneyAmount? = nil; var averageExecutionPrice: MoneyAmount? = nil; var createdAt: Date? = nil; var updatedAt: Date? = nil }
struct OpenPosition: Equatable, Sendable, Codable { let pair: String; let quantity: Decimal?; let averageExecutionPrice: MoneyAmount?; let costBasisPrice: MoneyAmount?; var id: String? = nil; var status: String? = nil; var side: String? = nil; var entryPrice: MoneyAmount? = nil; var currentPrice: MoneyAmount? = nil; var estimatedValueQuote: MoneyAmount? = nil; var unrealizedPnLQuote: MoneyAmount? = nil; var openedAt: Date? = nil; var origin: String? = nil; var reconciliationPending: Bool? = nil }
struct ProfitAndLoss: Equatable, Sendable, Codable { let gross: MoneyAmount?; let netEstimated: MoneyAmount?; let realizedNet: MoneyAmount? }
struct FeeAwareSummary: Equatable, Sendable, Codable { let executionPrice: MoneyAmount?; let costBasisPrice: MoneyAmount?; let buyFeeQuote: MoneyAmount?; let buyFeeRateEffective: Decimal?; let estimatedSellFeeQuote: MoneyAmount?; let estimatedSellFeeRate: Decimal?; let estimatedSellFeeSource: String?; let breakEvenPrice: MoneyAmount?; let minimumProfitableExitPrice: MoneyAmount?; let minimumNetProfitRate: Decimal?; let estimatedSlippageRate: Decimal?; let unrealizedPnLGrossQuote: MoneyAmount?; let unrealizedPnLNetEstimatedQuote: MoneyAmount?; let realizedPnLNetQuote: MoneyAmount?; let totalEstimatedCycleFeesQuote: MoneyAmount?; let liquidityRole: String? }
struct StrategyConditionSummary: Equatable, Sendable, Codable { let key: String?; let label: String?; let state: String?; let value: String?; let threshold: String?; let detail: String?; var presentationState: String { switch state?.lowercased() { case "ok", "validated", "strong_validated": "Favorable"; case "blocked", "veto", "invalid": "Défavorable"; default: "À confirmer" } } }
struct StrategyDecisionSummary: Equatable, Sendable, Codable { let title: String; let detail: String; let favorableConditions: Int?; let requiredConditions: Int?; var code: String? = nil; var score: Decimal? = nil; var scoreMin: Decimal? = nil; var controller: String? = nil; var blockers: [String] = []; var buyConditions: [StrategyConditionSummary] = []; var sellConditions: [StrategyConditionSummary] = []; var advice: [String] = []; var price: MoneyAmount? = nil; var createdAt: Date? = nil }

extension OrderStatus { init(backend: String?) { switch backend { case "submission_started": self = .submissionStarted; case "submitted": self = .submitted; case "open": self = .open; case "partially_filled", "partiallyFilled": self = .partiallyFilled; case "filled": self = .filled; case "reconciliation_required", "reconciliationRequired": self = .reconciliationRequired; case "reconciliation_blocked", "reconciliationBlocked": self = .reconciliationBlocked; case "reconciliation_failed", "reconciliationFailed": self = .reconciliationFailed; case "canceled", "cancelled": self = .canceled; case "rejected": self = .rejected; default: self = .unknown } } }
extension TradingProvider { init(backend: String?) { switch backend?.lowercased() { case "kraken": self = .kraken; case "binance", "binance_legacy": self = .binanceLegacy; default: self = .unknown } } }
