import Foundation

struct MoneyAmount: Equatable, Sendable, Codable { let value: Decimal?; let currency: String; init(_ value: Decimal?, currency: String = "USDC") { self.value = value; self.currency = currency } }
enum TradingProvider: String, CaseIterable, Sendable, Codable { case kraken, binanceLegacy, unknown; var displayName: String { switch self { case .kraken: "Kraken"; case .binanceLegacy: "Historique Binance"; case .unknown: "Provider inconnu" } } }
enum ExecutionMode: String, Sendable, Codable { case spotProduction, legacyReadOnly, demoFixture, unknown }
enum SessionLifecycleState: String, CaseIterable, Sendable, Codable { case waitingBuy, preparingBuy, waitingBuyFill, positionOpen, waitingSell, waitingSellFill, monitoringPosition, reconciliationPending, stopped, unknown
    var userMessage: String { switch self { case .waitingBuy: "Botaplata cherche une opportunité d'achat."; case .preparingBuy: "Botaplata prépare une intention d'achat. Aucun achat n'est envoyé depuis l'app."; case .waitingBuyFill: "L'ordre d'achat est en attente sur Kraken."; case .positionOpen, .waitingSell, .monitoringPosition: "Position ouverte. Botaplata surveille maintenant les conditions de sortie."; case .waitingSellFill: "L'ordre de vente est en attente de confirmation sur Kraken."; case .reconciliationPending: "Botaplata vérifie encore l'état de cet ordre sur Kraken."; case .stopped: "Session arrêtée."; case .unknown: "État de session inconnu." } }
    var label: String { switch self { case .waitingBuy: "Recherche BUY"; case .preparingBuy: "Préparation BUY"; case .waitingBuyFill: "BUY en attente"; case .positionOpen: "Position ouverte"; case .waitingSell: "Attente SELL"; case .waitingSellFill: "SELL en attente"; case .monitoringPosition: "Surveillance position"; case .reconciliationPending: "Vérification en cours"; case .stopped: "Arrêtée"; case .unknown: "Inconnu" } }
}
enum RuntimeHealthState: String, Sendable, Codable { case healthy, degraded, unavailable, unknown; var label: String { switch self { case .healthy: "Surveillance normale"; case .degraded: "Surveillance perturbée"; case .unavailable: "Surveillance indisponible"; case .unknown: "Santé inconnue" } } }
enum OrderStatus: String, CaseIterable, Sendable, Codable { case submitted, open, partiallyFilled, filled, reconciliationRequired, reconciliationBlocked, reconciliationFailed, canceled, rejected, unknown
    var label: String { switch self { case .submitted: "Envoyé"; case .open: "Ouvert"; case .partiallyFilled: "Partiellement exécuté"; case .filled: "Exécuté"; case .reconciliationRequired: "Vérification en cours"; case .reconciliationBlocked: "Réconciliation bloquée"; case .reconciliationFailed: "Vérification échouée"; case .canceled: "Annulé"; case .rejected: "Rejeté"; case .unknown: "Inconnu" } }
}
struct TradingOrderSummary: Identifiable, Equatable, Sendable, Codable { let id: String; let side: String; let status: OrderStatus; let message: String }
struct OpenPosition: Equatable, Sendable, Codable { let pair: String; let quantity: Decimal?; let averageExecutionPrice: MoneyAmount?; let costBasisPrice: MoneyAmount? }
struct ProfitAndLoss: Equatable, Sendable, Codable { let gross: MoneyAmount?; let netEstimated: MoneyAmount?; let realizedNet: MoneyAmount? }
struct FeeAwareSummary: Equatable, Sendable, Codable { let executionPrice: MoneyAmount?; let costBasisPrice: MoneyAmount?; let buyFeeQuote: MoneyAmount?; let buyFeeRateEffective: Decimal?; let estimatedSellFeeQuote: MoneyAmount?; let estimatedSellFeeRate: Decimal?; let estimatedSellFeeSource: String?; let breakEvenPrice: MoneyAmount?; let minimumProfitableExitPrice: MoneyAmount?; let minimumNetProfitRate: Decimal?; let estimatedSlippageRate: Decimal?; let unrealizedPnLGrossQuote: MoneyAmount?; let unrealizedPnLNetEstimatedQuote: MoneyAmount?; let realizedPnLNetQuote: MoneyAmount?; let totalEstimatedCycleFeesQuote: MoneyAmount?; let liquidityRole: String? }
struct StrategyDecisionSummary: Equatable, Sendable, Codable { let title: String; let detail: String; let favorableConditions: Int?; let requiredConditions: Int? }

extension OrderStatus { init(backend: String?) { switch backend { case "submitted": self = .submitted; case "open": self = .open; case "partially_filled", "partiallyFilled": self = .partiallyFilled; case "filled": self = .filled; case "reconciliation_required", "reconciliationRequired": self = .reconciliationRequired; case "reconciliation_blocked", "reconciliationBlocked": self = .reconciliationBlocked; case "reconciliation_failed", "reconciliationFailed": self = .reconciliationFailed; case "canceled", "cancelled": self = .canceled; case "rejected": self = .rejected; default: self = .unknown } } }
extension TradingProvider { init(backend: String?) { switch backend?.lowercased() { case "kraken": self = .kraken; case "binance", "binance_legacy": self = .binanceLegacy; default: self = .unknown } } }
